/* =========================================================================
   KlugRads — Biblioteca de frases de alteração (laudos de US)
   ---------------------------------------------------------------------------
   Redação própria do KlugRads. Temas organizados com base no laudário de
   referência enviado pelo usuário e no compêndio indicado (apenas como guia
   do que costuma ser descrito; o texto não foi copiado).

   Campos:
     o  órgão (chave de LAU_FRASE_ORGAOS)
     n  nome no botão
     m  'sub' substitui o texto do item | 'add' acrescenta uma linha
     t  texto do laudo — XXX = campo; "a XX b" = escolha
     c  conclusão; {0}, {1}… = valor do campo/escolha nº 0, 1… do texto;
        {L} = rótulo do item (ex.: "mama direita")
     x  negativas a retirar do texto padrão quando a frase é acrescentada
     s  1 = já coberta pelos controles estruturados do órgão (fica oculta)
     kind 'tirads' | 'birads' = frase com classificação (descritores +
          categoria; TI-RADS usa a mesma pontuação da calculadora)
     br categoria BI-RADS da frase (entra na categoria final do exame)
     kind 'tend' | 'musc' | 'lig' = escolha do tendão/músculo (lista por articulação) e do tipo de lesão
     so  lista de laudos em que a frase aparece (ex.: só no ombro)
     vaz trechos que somem do laudo quando o campo (XXX) não for preenchido
     q  1 = aceita quantidade (único / vários semelhantes / diferentes); cp = conclusão no plural
   ========================================================================= */

/* rótulo do item (normalizado, sem acento) → órgão da biblioteca */
const LAU_FRASE_ORGAOS = [
  ['figado', /^figado/],
  ['porta', /veias? porta|porta e hepat/],
  ['vesicula', /^vesicula biliar/],
  ['vias', /^vias biliares/],
  ['pancreas', /^pancreas/],
  ['baco', /^baco/],
  ['rins', /^rins?\b|^rim /],
  ['bexiga', /^bexiga/],
  ['prostata', /^prostata/],
  ['aorta', /^aorta/],
  ['iliaca', /^aorta, arterias iliacas|^arterias iliacas/],
  ['peritoneo', /^peritoneo/],
  ['tireoide', /^tireoide|^lobo (direito|esquerdo)|^istmo/],
  ['linfonodos', /linfonod/],
  ['salivares', /parotida|submandibular|glandulas? salivar/],
  ['testiculo', /^testicul/],
  ['bolsapar', /^parede da bolsa|^bolsa/],
  ['liqbolsa', /^liquido na bolsa/],
  ['epididimo', /^epididimo/],
  ['pampiniforme', /pampiniform/],
  ['utero', /^utero/],
  ['miometrio', /^miometrio/],
  ['endometrio', /^endometrio/],
  ['ovario', /^ovario/],
  ['pelesub', /^pele e tecido subcutaneo/],
  ['canalinguinal', /^canal inguinal/],
  ['partes', /formac|massas|^coleco|tecido|subcutane|^pele|^lesoes|^lesao/],
  ['pleura', /pleura|cupula|hemitorax/],
  ['pericardio', /^pericardi/],
  ['mama', /^mama (direita|esquerda)/],
  ['ductos', /retroareolar|^ductos/],
  ['axila', /axila/],
  ['comparacao', /^comparac/],
  ['__extra', /^__extra$/],
  ['__extracerv', /^__extracerv$/],
  /* musculoesquelético */
  ['tendao', /^tend(ao|oes)|tendine|^trato iliotibial|^compartimentos sinoviais|^compartimento (anterior|medial|lateral)/],
  ['bursa', /^bursa|^bursite/],
  ['derrame', /^derrame articular|^sinfise/],
  ['acromio', /acromioclavicular/],
  ['poplitea', /^fossa poplitea/],
  ['cotfossas', /^fossas coronoide/],
  ['ligamento', /^ligamento/],
  ['fascia', /^fascia plantar/],
  ['nervo', /^nervo/],
  ['musculo', /^planos musculares|^ventres? musculares|^musculatura|^ventres musculares/],
  ['interdigital', /^espacos interdigitais/],
  ['hernia', /^hernias?/],
  /* vascular */
  ['carotida', /carotida|medio-intima/],
  ['vertebral', /^arterias? vertebra/],
  ['arterial', /^arteri(a|as) (femora|poplit|tibia|subclav|axilar|braqui|radia)|^arterias femorais|^arterias subclavias|^arterias radiais/],
  ['venoso', /^veias? (cava|femora|poplit|tibia|subclav|axilar|braqui)|^- veias cava/],
  ['varizes', /safena|perfurant|incompetencia|refluxo/],
  ['renalart', /^arterias renais|^velocidades de pico|intrarrenais|^relac/],
  ['temporal', /^arterias temporais/],
  ['veiafav', /^veia (cefalica|basilica)/],
];

const LAU_FRASES = [
  /* ---------------- ACHADO GERAL: ateromatose sem estenose (Doppler arterial dos MMII; marcado no quadro do topo do laudo) ---------------- */
  {o:'artgeral', n:'Ateromatose sem estenoses significativas', m:'add',
   t:'Ateromatose leve XX moderada XX difusa no leito arterial estudado, com placas parietais parcialmente calcificadas esparsas, sem determinar estenoses hemodinamicamente significativas.',
   c:'Ateromatose no leito arterial estudado sem determinar estenoses hemodinamicamente significativas.'},
  /* ---------------- FÍGADO ---------------- */
  {o:'figado', s:1, n:'Hepatomegalia', m:'sub',
   t:'com dimensões aumentadas (lobo direito medindo XXX cm), contornos regulares e bordas finas. Ecotextura parenquimatosa hepática homogênea.',
   c:'Hepatomegalia homogênea.'},
  {o:'figado', s:1, n:'Esteatose', m:'sub',
   t:'com dimensões normais, contornos regulares e bordas finas. Ecogenicidade parenquimatosa difusamente aumentada, de grau leve XX moderado XX acentuado.',
   c:'Esteatose hepática de grau {0}.'},
  {o:'figado', n:'Esteatose com área de preservação', m:'add',
   t:'Área hipoecogênica mal definida no segmento XXX, medindo XXX cm, compatível com área de parênquima poupado pela infiltração gordurosa.',
   c:'Área focal de preservação gordurosa no segmento {0}.'},
  {o:'figado', s:1, n:'Hepatopatia crônica', m:'sub',
   t:'com contornos lobulados, bordas rombas e lobo caudado proeminente. Ecotextura parenquimatosa difusamente heterogênea e grosseira.',
   c:'Sinais ultrassonográficos de hepatopatia crônica.'},
  {o:'figado', n:'Fibrose periportal', m:'sub',
   t:'com contornos discretamente irregulares e aumento da ecogenicidade periportal difusa, com espessamento das paredes dos ramos portais.',
   c:'Sinais de fibrose periportal (correlacionar com esquistossomose).'},
  {o:'figado', n:'Hepatite aguda (padrão)', m:'add',
   t:'Discreto aumento da ecogenicidade das paredes dos ramos portais, em contraste com parênquima de ecogenicidade reduzida.',
   c:'Alteração parenquimatosa hepática difusa, que pode estar relacionada a hepatite aguda, a critério clínico-laboratorial.'},
  {o:'figado', q:1, cp:'Cistos hepáticos simples.', s:1, n:'Cisto simples', m:'add', les:1,
   t:'Imagem cística de paredes finas, conteúdo anecogênico e reforço acústico posterior no segmento XXX, medindo XXX cm.',
   c:'Cisto hepático simples.'},
  {o:'figado', q:1, cp:'Nódulos hepáticos com aspecto sugestivo de hemangiomas.', s:1, n:'Hemangioma', m:'add', les:1,
   t:'Nódulo hiperecogênico, homogêneo, de contornos bem definidos, sem sombra acústica, no segmento XXX, medindo XXX cm.',
   c:'Nódulo hepático com aspecto sugestivo de hemangioma.'},
  {o:'figado', q:1, cp:'Calcificações hepáticas de aspecto residual.', s:1, n:'Calcificação', m:'add', les:1,
   t:'Foco hiperecogênico com sombra acústica posterior no segmento XXX, medindo XXX cm.',
   c:'Calcificação hepática de aspecto residual.'},
  {o:'figado', q:1, cp:'Nódulos hepáticos sólidos indeterminados. Sugere-se complementação com TC ou RM com contraste.', s:1, n:'Nódulo sólido indeterminado', m:'add', les:1,
   t:'Nódulo sólido hipoecogênico XX hiperecogênico XX heterogêneo no segmento XXX, medindo XXX cm.',
   c:'Nódulo hepático sólido indeterminado. Sugere-se complementação com TC ou RM com contraste.'},
  {o:'figado', n:'Nódulos com halo (secundário?)', m:'add', les:1,
   t:'Múltiplos nódulos sólidos com halo hipoecogênico, esparsos pelo parênquima, o maior no segmento XXX, medindo XXX cm.',
   c:'Múltiplos nódulos hepáticos sólidos; considerar a possibilidade de lesões secundárias.'},
  {o:'figado', n:'Lesão cística complexa (abscesso?)', m:'add', les:1,
   t:'Lesão cística de paredes espessas e irregulares, com conteúdo espesso e debris, no segmento XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Lesão cística complexa no segmento {0}; considerar abscesso, a critério clínico.'},
  {o:'figado', n:'Lobo de Riedel', m:'add',
   t:'Alongamento do lobo hepático direito, medindo XXX cm no eixo longitudinal, com morfologia preservada (variante anatômica — lobo de Riedel).',
   c:''},
  {o:'figado', n:'Avaliação limitada por esteatose', m:'add',
   t:'A atenuação do feixe acústico pela alteração difusa reduz a sensibilidade do método para lesões focais.', c:''},

  /* ---------------- VEIAS PORTA / HEPÁTICAS ---------------- */
  {o:'porta', s:1, n:'Hipertensão portal', m:'sub',
   t:'veia porta com calibre aumentado, medindo XXX cm, e vasos colaterais dilatados e tortuosos no território XXX. Veias hepáticas pérvias.',
   c:'Sinais de hipertensão portal.'},
  {o:'porta', n:'Trombose da veia porta', m:'sub',
   t:'veia porta com calibre de XXX cm, preenchida por material ecogênico no segmento extra-hepático XX intra-hepático. Veias hepáticas com calibres preservados.',
   c:'Sinais de trombose da veia porta.'},
  {o:'porta', s:1, n:'Congestão (veias hepáticas dilatadas)', m:'sub',
   t:'veia porta com calibre preservado. Veias hepáticas e veia cava inferior dilatadas.',
   c:'Dilatação das veias hepáticas e da veia cava inferior, que pode estar relacionada a congestão hepática.'},

  /* ---------------- VESÍCULA BILIAR ---------------- */
  {o:'vesicula', s:1, n:'Colelitíase (cálculo único)', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo cálculo móvel com sombra acústica posterior, medindo XXX cm.',
   c:'Colelitíase.'},
  {o:'vesicula', s:1, n:'Colelitíase (múltiplos)', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo múltiplos cálculos móveis com sombra acústica posterior, o maior medindo XXX cm.',
   c:'Colelitíase.'},
  {o:'vesicula', n:'Colelitíase + lama biliar', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo material ecogênico pendente sem sombra (lama biliar) e cálculo(s) com sombra acústica posterior, o maior medindo XXX cm.',
   c:'Colelitíase e lama biliar.'},
  {o:'vesicula', s:1, n:'Lama biliar', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo material ecogênico pendente, sem sombra acústica, formando nível líquido-líquido (lama biliar).',
   c:'Lama biliar. A lama pode mascarar microcálculos.'},
  {o:'vesicula', s:1, n:'Colecistite aguda litiásica', m:'sub',
   t:'distendida, com paredes espessadas e edemaciadas, medindo até XXX cm, contendo cálculo(s) com sombra acústica, o maior medindo XXX cm. Sinal de Murphy ultrassonográfico positivo.',
   c:'Achados sugestivos de colecistite aguda litiásica.'},
  {o:'vesicula', n:'Vesícula escleroatrófica', m:'sub',
   t:'contraída, com lúmen ocupado por cálculo(s) e extensa sombra acústica posterior (complexo parede-eco-sombra), medindo cerca de XXX cm.',
   c:'Colelitíase com vesícula biliar escleroatrófica.'},
  {o:'vesicula', q:1, cp:'Pólipos na vesícula biliar (o maior com {1} cm).', s:1, n:'Pólipo', m:'add',
   t:'Imagem polipoide ecogênica, fixa, sem sombra acústica, aderida à parede XXX, medindo XXX cm.',
   c:'Pólipo na vesícula biliar ({1} cm).'},
  {o:'vesicula', n:'Colesterolose', m:'add',
   t:'Pequenos focos ecogênicos parietais com artefato em cauda de cometa, sem cálculos.',
   c:'Colesterolose vesicular.'},
  {o:'vesicula', n:'Adenomiomatose', m:'add',
   t:'Espessamento parietal segmentar XX difuso XX fúndico, de até XXX cm, com pequenos espaços císticos e focos com artefato em cauda de cometa.',
   c:'Achados sugestivos de adenomiomatose da vesícula biliar.'},
  {o:'vesicula', s:1, n:'Colecistectomia', m:'sub',
   t:'não caracterizada (status pós-colecistectomia).',
   c:'Status pós-colecistectomia.'},

  /* ---------------- VIAS BILIARES ---------------- */
  {o:'vias', s:1, n:'Dilatação intra e extra-hepática', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm.',
   c:'Dilatação das vias biliares intra e extra-hepáticas.'},
  {o:'vias', s:1, n:'Coledocolitíase', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm e imagem ecogênica com sombra acústica em sua porção distal, medindo XXX cm, sugestiva de cálculo.',
   c:'Dilatação das vias biliares por provável coledocolitíase.'},
  {o:'vias', n:'Dilatação com obstrução distal', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm, com afilamento abrupto distal junto à cabeça pancreática.',
   c:'Dilatação das vias biliares com afilamento distal; prosseguir investigação com método seccional.'},
  {o:'vias', n:'Dilatação intra-hepática hilar', m:'sub',
   t:'dilatação das vias biliares intra-hepáticas, com aparente interrupção na região hilar; colédoco de calibre preservado.',
   c:'Dilatação das vias biliares intra-hepáticas com obstrução hilar; prosseguir investigação com método seccional.'},
  {o:'vias', n:'Aerobilia', m:'add',
   t:'Focos ecogênicos lineares com artefato de reverberação nas vias biliares, compatíveis com aerobilia.',
   c:'Aerobilia.'},

  /* ---------------- PÂNCREAS ---------------- */
  {o:'pancreas', s:1, n:'Não caracterizado (gases)', m:'sub',
   t:'não caracterizado devido à interposição gasosa intestinal.', c:''},
  {o:'pancreas', n:'Parcialmente avaliado (gases)', m:'sub',
   t:'cabeça e corpo com dimensões, contornos e ecogenicidade normais; cauda não caracterizada devido à interposição gasosa.', c:''},
  {o:'pancreas', s:1, n:'Lipossubstituição', m:'sub',
   t:'com dimensões e contornos normais e ecogenicidade difusamente aumentada.',
   c:'Aumento difuso da ecogenicidade pancreática, compatível com lipossubstituição.'},
  {o:'pancreas', n:'Pancreatite aguda (padrão)', m:'sub',
   t:'com dimensões aumentadas, ecogenicidade reduzida e contornos borrados, com líquido peripancreático.',
   c:'Alterações pancreáticas que podem corresponder a pancreatite aguda, a critério clínico-laboratorial.'},
  {o:'pancreas', n:'Pancreatopatia crônica', m:'sub',
   t:'com contornos lobulados, calcificações parenquimatosas e ducto pancreático principal dilatado, medindo XXX cm.',
   c:'Sinais de pancreatopatia crônica.'},
  {o:'pancreas', s:1, n:'Lesão cística', m:'add',
   t:'Imagem cística na cabeça XX corpo XX cauda pancreática, medindo XXX cm.',
   c:'Lesão cística pancreática. Sugere-se complementação com RM e colangiorressonância.'},
  {o:'pancreas', n:'Massa sólida', m:'add',
   t:'Massa sólida hipoecogênica na cabeça XX corpo XX cauda pancreática, medindo XXX cm.',
   c:'Massa sólida pancreática; prosseguir investigação com método seccional.'},

  /* ---------------- BAÇO ---------------- */
  {o:'baco', s:1, n:'Esplenomegalia', m:'sub',
   t:'com dimensões aumentadas, medindo XXX cm no maior eixo, homogêneo.',
   c:'Esplenomegalia ({0} cm).'},
  {o:'baco', s:1, n:'Baço acessório', m:'add',
   t:'Pequeno nódulo junto ao hilo esplênico, com ecogenicidade semelhante à do baço, medindo XXX cm, compatível com baço acessório.',
   c:''},
  {o:'baco', s:1, n:'Granulomas calcificados', m:'add', les:1,
   t:'Focos hiperecogênicos esparsos com sombra acústica posterior, compatíveis com granulomas calcificados.',
   c:'Granulomas calcificados esplênicos.'},
  {o:'baco', q:1, cp:'Nódulos esplênicos com aspecto sugestivo de hemangiomas.', n:'Hemangioma', m:'add', les:1,
   t:'Nódulo hiperecogênico, homogêneo e bem definido no terço superior XX médio XX inferior, medindo XXX cm.',
   c:'Nódulo esplênico com aspecto sugestivo de hemangioma.'},
  {o:'baco', s:1, n:'Esplenectomia', m:'sub',
   t:'não caracterizado (status pós-esplenectomia).',
   c:'Status pós-esplenectomia.'},
  {o:'baco', n:'Esplenose', m:'add',
   t:'Nódulos sólidos com ecotextura semelhante à esplênica na loja esplênica, medindo até XXX cm.',
   c:'Nódulos na loja esplênica, sugestivos de esplenose.'},

  /* ---------------- RINS ---------------- */
  {o:'rins', q:1, cp:'Nefrolitíase não obstrutiva no rim {1}.', x:['cálculos','cálculo'], s:1, n:'Cálculo não obstrutivo', m:'add',
   t:'Cálculo no grupo calicinal superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm, sem dilatação do sistema coletor.',
   c:'Nefrolitíase não obstrutiva no rim {1}.'},
  {o:'rins', n:'Foco ecogênico sem sombra (cálculo?)', m:'add',
   t:'Pequeno foco ecogênico sem sombra acústica no rim direito XX esquerdo, medindo XXX cm.',
   c:'Pequeno foco ecogênico renal; não se pode excluir microcálculo.'},
  {o:'rins', x:['hidronefrose','dilatação'], s:1, n:'Hidronefrose', m:'add',
   t:'Dilatação leve XX moderada XX acentuada do sistema pielocalicinal do rim direito XX esquerdo.',
   c:'Hidronefrose {0} no rim {1}.'},
  {o:'rins', x:['hidronefrose','dilatação','cálculos','cálculo'], n:'Ureterolitíase com dilatação', m:'add',
   t:'Cálculo no ureter proximal XX distal direito XX esquerdo, medindo XXX cm, com uretero-hidronefrose a montante.',
   c:'Ureterolitíase no ureter {0} {1}, com uretero-hidronefrose a montante.'},
  {o:'rins', q:1, cp:'Cistos renais simples no rim {1}.', s:1, n:'Cisto renal simples', m:'add',
   t:'Cisto simples no terço superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm.',
   c:'Cisto renal simples no rim {1}.'},
  {o:'rins', n:'Rins policísticos', m:'sub',
   t:'tópicos, aumentados, com múltiplos cistos de tamanhos variados substituindo o parênquima bilateralmente, o maior medindo XXX cm.',
   c:'Múltiplos cistos renais bilaterais; considerar doença renal policística.'},
  {o:'rins', q:1, cp:'Nódulos renais com aspecto sugestivo de angiomiolipomas.', n:'Angiomiolipoma', m:'add',
   t:'Nódulo hiperecogênico, homogêneo e bem definido no terço superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm.',
   c:'Nódulo renal com aspecto sugestivo de angiomiolipoma.'},
  {o:'rins', n:'Nefropatia crônica', m:'sub',
   t:'tópicos, com dimensões reduzidas (RD = XXX cm; RE = XXX cm), contornos irregulares, ecogenicidade parenquimatosa aumentada e redução da diferenciação corticomedular.',
   c:'Sinais de nefropatia parenquimatosa crônica bilateral.'},
  {o:'rins', n:'Nefrocalcinose medular', m:'add',
   t:'Pirâmides renais hiperecogênicas bilateralmente, com tênue sombra acústica.',
   c:'Sinais de nefrocalcinose medular.'},
  {o:'rins', n:'Duplicidade pielocalicinal', m:'add',
   t:'Seio renal com banda de parênquima separando os grupos calicinais no rim direito XX esquerdo, sugerindo duplicidade pielocalicinal.',
   c:''},
  {o:'rins', n:'Rim pélvico', m:'add',
   t:'Rim direito XX esquerdo em topografia pélvica, medindo XXX cm.',
   c:'Rim {0} ectópico pélvico.'},
  {o:'rins', n:'Rim em ferradura', m:'add',
   t:'Polos inferiores renais unidos por istmo de parênquima anterior à aorta.',
   c:'Rim em ferradura.'},
  {o:'rins', s:1, n:'Nefrectomia', m:'add',
   t:'Rim direito XX esquerdo não caracterizado (status pós-nefrectomia).',
   c:'Status pós-nefrectomia (rim {0}).'},
  {o:'rins', n:'Agenesia?', m:'add',
   t:'Rim direito XX esquerdo não caracterizado na loja renal nem na pelve.',
   c:'Rim {0} não caracterizado; considerar agenesia ou ectopia.'},
  {o:'rins', n:'Cateter duplo J', m:'add',
   t:'Cateter de duplo J à direita XX esquerda, com extremidades no sistema pielocalicinal e na bexiga.',
   c:'Cateter de duplo J à {0}.'},

  /* ---------------- BEXIGA ---------------- */
  {o:'bexiga', n:'Espessamento difuso (esforço)', m:'sub',
   t:'com paredes difusamente espessadas e trabeculadas, medindo até XXX cm, com pseudodivertículos.',
   c:'Bexiga de esforço.'},
  {o:'bexiga', n:'Espessamento difuso (cistite?)', m:'sub',
   t:'com paredes difusamente espessadas, medindo até XXX cm, e conteúdo anecogênico.',
   c:'Espessamento parietal vesical difuso; considerar cistite, a critério clínico.'},
  {o:'bexiga', q:1, cp:'Litíase vesical.', x:[], s:1, n:'Cálculo vesical', m:'add',
   t:'Imagem ecogênica móvel com sombra acústica em seu interior, medindo XXX cm.',
   c:'Litíase vesical.'},
  {o:'bexiga', n:'Lesão parietal vegetante', m:'add',
   t:'Lesão sólida vegetante, fixa, na parede XXX, medindo XXX cm.',
   c:'Lesão vegetante vesical; prosseguir investigação (cistoscopia).'},
  {o:'bexiga', n:'Coágulo', m:'add',
   t:'Material ecogênico heterogêneo, móvel, no assoalho vesical, medindo XXX cm, sugestivo de coágulo.',
   c:'Imagem sugestiva de coágulo intravesical.'},
  {o:'bexiga', s:1, n:'Sonda vesical', m:'add',
   t:'Balão de sonda vesical no interior da bexiga.', c:''},
  {o:'bexiga', n:'Resíduo pós-miccional', m:'add',
   t:'Resíduo pós-miccional estimado em XXX mL.',
   c:'Resíduo pós-miccional de {0} mL.'},

  /* ---------------- PRÓSTATA ---------------- */
  {o:'prostata', n:'Aumentada (hiperplasia)', m:'sub',
   t:'com dimensões aumentadas, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³), ecotextura heterogênea e contornos regulares.',
   c:'Próstata aumentada ({3} cm³).'},
  {o:'prostata', n:'Calcificações', m:'add',
   t:'Focos de calcificação no parênquima prostático.', c:''},
  {o:'prostata', n:'Protrusão intravesical', m:'add',
   t:'Protrusão do lobo mediano na base vesical, medindo XXX cm.',
   c:'Protrusão prostática intravesical ({0} cm).'},

  /* ---------------- AORTA ---------------- */
  {o:'aorta', s:1, n:'Ateromatose', m:'sub',
   t:'com calibre normal e placas parietais calcificadas.', c:'Ateromatose aórtica.'},
  {o:'aorta', s:1, n:'Aneurisma', m:'sub',
   t:'com dilatação aneurismática fusiforme XX sacular no segmento infrarrenal, medindo XXX cm de diâmetro máximo e XXX cm de extensão.',
   c:'Aneurisma da aorta abdominal infrarrenal ({1} cm).'},
  {o:'aorta', s:1, n:'Aneurisma com trombo mural', m:'add',
   t:'Trombo mural laminar reduzindo parcialmente a luz.', c:''},

  /* ---------------- PERITÔNEO / RETROPERITÔNIO ---------------- */
  {o:'peritoneo', s:1, n:'Ascite', m:'sub',
   t:'pequena XX moderada XX grande quantidade de líquido livre na cavidade abdominal.',
   c:'Ascite ({0} quantidade).'},
  {o:'peritoneo', n:'Líquido com debris (sangue?)', m:'sub',
   t:'líquido livre com debris na cavidade abdominal, em quantidade pequena XX moderada XX grande.',
   c:'Líquido livre com debris; considerar hemoperitônio, a critério clínico.'},
  {o:'peritoneo', x:['coleções','coleção'], s:1, n:'Coleção', m:'add',
   t:'Coleção em XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Coleção em {0}.'},
  {o:'peritoneo', s:1, n:'Linfonodomegalia retroperitoneal', m:'add',
   t:'Linfonodos retroperitoneais aumentados, o maior medindo XXX cm no menor eixo.',
   c:'Linfonodomegalia retroperitoneal.'},

  /* ---------------- ACHADOS ADICIONAIS (pescoço: carótidas, vertebrais, temporais) ---------------- */
  {o:'__extracerv', n:'Nódulo tireoidiano', m:'add', medOpc:1,
   t:'Nódulo sólido XX cístico XX misto no lobo direito XX esquerdo da tireoide, medindo XXX x XXX x XXX cm, incidentalmente caracterizado.',
   c:'Nódulo tireoidiano incidental. Sugere-se ultrassonografia dedicada da tireoide para caracterização.'},
  {o:'__extracerv', n:'Nódulos tireoidianos', m:'add', medOpc:1,
   t:'Nódulos tireoidianos bilaterais, o maior no lobo direito XX esquerdo, medindo XXX x XXX x XXX cm, incidentalmente caracterizados.',
   c:'Nódulos tireoidianos incidentais. Sugere-se ultrassonografia dedicada da tireoide para caracterização.'},
  {o:'__extracerv', n:'Cisto tireoidiano', m:'add', medOpc:1,
   t:'Cisto simples no lobo direito XX esquerdo da tireoide, medindo XXX x XXX x XXX cm.',
   c:'Cisto tireoidiano.'},
  {o:'__extracerv', n:'Tireoide heterogênea / aumentada', m:'add',
   t:'Tireoide de dimensões aumentadas XX normais e ecotextura heterogênea, incidentalmente caracterizada.',
   c:'Tireoide heterogênea. Sugere-se ultrassonografia dedicada da tireoide.'},
  {o:'__extracerv', n:'Linfonodo atípico', m:'add', medOpc:1,
   t:'Linfonodo cervical no nível XXX à direita XX à esquerda, com perda do hilo ecogênico, medindo XXX x XXX cm.',
   c:'Linfonodo cervical de aspecto atípico. Sugere-se avaliação ultrassonográfica cervical dedicada.'},
  {o:'__extracerv', n:'Linfonodos reacionais', m:'add',
   t:'Linfonodos cervicais de aspecto reacional, com hilo ecogênico preservado.',
   c:''},
  {o:'__extracerv', n:'Glândula submandibular / parótida', m:'add', medOpc:1,
   t:'Nódulo na glândula XXX, medindo XXX x XXX x XXX cm, incidentalmente caracterizado.',
   c:'Nódulo em glândula salivar ({0}). Sugere-se avaliação dedicada.'},

  /* ---------------- ACHADOS ADICIONAIS (abdome) ---------------- */
  {o:'__extra', n:'Apendicite (padrão)', m:'add',
   t:'Estrutura tubular em fundo cego na fossa ilíaca direita, não compressível, com diâmetro de XXX cm, com borramento da gordura adjacente.',
   c:'Achados sugestivos de apendicite aguda.'},
  {o:'__extra', n:'Apêndice não caracterizado', m:'add',
   t:'Apêndice cecal não caracterizado; sem borramento da gordura ou coleções na fossa ilíaca direita.',
   c:''},
  {o:'__extra', n:'Adenite mesentérica', m:'add',
   t:'Linfonodos mesentéricos aumentados na fossa ilíaca direita, o maior medindo XXX cm no menor eixo, sem borramento da gordura.',
   c:'Linfonodos mesentéricos aumentados; considerar adenite mesentérica.'},
  {o:'__extra', n:'Intussuscepção', m:'add',
   t:'Imagem em alvo no XXX, medindo XXX cm, compatível com invaginação intestinal.',
   c:'Sinais de intussuscepção intestinal.'},
  {o:'__extra', n:'Espessamento de alça', m:'add',
   t:'Espessamento parietal de alça XXX, medindo até XXX cm, com borramento da gordura adjacente.',
   c:'Espessamento parietal de alça intestinal; considerar processo inflamatório/infeccioso.'},
  {o:'__extra', n:'Hérnia', m:'add',
   t:'Hérnia XXX com colo de XXX cm, contendo gordura XX intestino, redutível XX irredutível.',
   c:'Hérnia {0}.'},

  /* ---------------- TIREOIDE ---------------- */
  {o:'tireoide', q:1, n:'Nódulo (TI-RADS)', m:'add', kind:'tirads', x:['lesões nodulares','císticas'],
   t:'no terço superior XX médio XX inferior do lobo direito XX esquerdo, medindo XXX x XXX x XXX cm'},
  {o:'tireoide', q:1, cp:'Cistos tireoidianos.', x:['lesões nodulares','císticas'], n:'Cisto', m:'add',
   t:'Cisto anecogênico no lobo direito XX esquerdo, medindo XXX cm.',
   c:'Cisto tireoidiano.'},
  {o:'tireoide', n:'Bócio', m:'sub',
   t:'tópica, com dimensões aumentadas (volume total de XXX cm³), contornos regulares e textura heterogênea.',
   c:'Bócio.'},
  {o:'tireoide', n:'Tireoidopatia difusa', m:'sub',
   t:'tópica, com dimensões normais XX aumentadas XX reduzidas, textura difusamente heterogênea e vascularização aumentada XX preservada ao Doppler.',
   c:'Tireoidopatia difusa; correlacionar com função tireoidiana e anticorpos.'},
  {o:'tireoide', n:'Tireoidectomia total', m:'sub',
   t:'não caracterizada (status pós-tireoidectomia total).', c:'Status pós-tireoidectomia total.'},
  {o:'tireoide', n:'Tireoidectomia parcial', m:'add',
   t:'Lobo direito XX esquerdo não caracterizado (status pós-operatório).', c:'Status pós-lobectomia tireoidiana (lobo {0}).'},

  /* ---------------- LINFONODOS (cervical etc.) ---------------- */
  {o:'linfonodos', n:'Linfonodos de aspecto reacional', m:'sub',
   t:'linfonodos de aspecto habitual (hilo ecogênico preservado) no nível XXX, o maior medindo XXX cm no menor eixo.', c:''},
  {o:'linfonodos', n:'Linfonodomegalia suspeita', m:'sub',
   t:'linfonodos aumentados, arredondados, com perda do hilo ecogênico, no nível XXX, o maior medindo XXX cm no menor eixo.',
   c:'Linfonodomegalia de aspecto suspeito no nível {0}.'},

  /* ---------------- GLÂNDULAS SALIVARES ---------------- */
  {o:'salivares', n:'Sialoadenite', m:'add',
   t:'Glândula parótida XX submandibular direita XX esquerda aumentada, heterogênea e hipervascularizada ao Doppler.',
   c:'Sinais de sialoadenite.'},
  {o:'salivares', n:'Sialolitíase', m:'add',
   t:'Cálculo no ducto da glândula XXX, medindo XXX cm, com dilatação ductal a montante.',
   c:'Sialolitíase.'},
  {o:'salivares', q:1, cp:'Nódulos em glândula salivar; prosseguir investigação.', n:'Nódulo', m:'add',
   t:'Nódulo sólido na glândula XXX, medindo XXX cm.',
   c:'Nódulo em glândula salivar; prosseguir investigação.'},

  /* ---------------- BOLSA TESTICULAR ---------------- */
  /* bolsa testicular — cada item com as suas frases */
  {o:'bolsapar', n:'Espessamento / edema', m:'sub',
   t:'espessada e edemaciada à direita XX à esquerda XX bilateralmente.',
   c:'Espessamento e edema da parede da bolsa testicular {0}.'},
  {o:'liqbolsa', n:'Hidrocele', m:'sub',
   t:'pequena XX moderada XX grande quantidade de líquido anecogênico na túnica vaginal à direita XX à esquerda XX bilateralmente.',
   c:'Hidrocele {1}.'},
  {o:'liqbolsa', n:'Líquido com debris / septações', m:'sub',
   t:'líquido com ecos internos e septações na túnica vaginal à direita XX à esquerda, podendo corresponder a hematocele ou piocele, a critério clínico.',
   c:'Coleção complexa na túnica vaginal {0}.'},
  {o:'pampiniforme', n:'Varicocele direita', m:'sub', medOpc:1,
   t:'veias do plexo pampiniforme direito dilatadas, medindo até XXX cm, com refluxo à manobra de Valsalva; à esquerda, veias de calibre normal.',
   c:'Varicocele à direita.'},
  {o:'pampiniforme', n:'Varicocele esquerda', m:'sub', medOpc:1,
   t:'veias do plexo pampiniforme esquerdo dilatadas, medindo até XXX cm, com refluxo à manobra de Valsalva; à direita, veias de calibre normal.',
   c:'Varicocele à esquerda.'},
  {o:'pampiniforme', n:'Varicocele bilateral', m:'sub', medOpc:1,
   t:'veias dos plexos pampiniformes dilatadas bilateralmente, medindo até XXX cm, com refluxo à manobra de Valsalva.',
   c:'Varicocele bilateral.'},
  {o:'epididimo', q:1, cp:'Cistos de epidídimo.', n:'Cisto de epidídimo', m:'add',
   t:'Cisto na cabeça XX corpo XX cauda do epidídimo direito XX esquerdo, medindo XXX cm.',
   c:'Cisto de epidídimo.'},
  {o:'epididimo', n:'Epididimite', m:'sub',
   t:'epidídimo direito XX esquerdo aumentado, heterogêneo e hipervascularizado ao Doppler.', contra:'Epidídimo {X} com dimensões normais e ecotextura característica.',
   c:'Sinais de epididimite no epidídimo {0}.'},
  {o:'testiculo', n:'Microlitíase', m:'add', td:'com múltiplos pequenos focos ecogênicos sem sombra acústica no parênquima (microlitíase)',
   t:'Múltiplos pequenos focos ecogênicos sem sombra acústica no parênquima testicular direito XX esquerdo XX bilateral.',
   c:'Microlitíase testicular.'},
  {o:'testiculo', q:1, cp:'Nódulos testiculares sólidos; correlação com marcadores e avaliação urológica.', n:'Nódulo testicular', m:'add',
   t:'Nódulo sólido hipoecogênico no testículo direito XX esquerdo, medindo XXX cm, com fluxo ao Doppler.',
   c:'Nódulo testicular sólido; correlação com marcadores e avaliação urológica.'},
  {o:'testiculo', n:'Orquite', m:'add', td:'de dimensões aumentadas, com ecotextura heterogênea e hipoecogênica e aumento da vascularização ao Doppler',
   t:'Testículo direito XX esquerdo de dimensões aumentadas, com ecotextura heterogênea e hipoecogênica e aumento da vascularização ao Doppler.',
   c:'Sinais de orquite no testículo {0}.'},
  {o:'testiculo', n:'Ausência de fluxo (torção?)', m:'add', td:'com ecotextura heterogênea, sem fluxo detectável ao Doppler, com funículo espermático espiralado',
   t:'Testículo direito XX esquerdo heterogêneo, sem fluxo detectável ao Doppler, com funículo espermático espiralado.',
   c:'Achados compatíveis com torção do testículo {0}. Avaliação urológica imediata.'},

  /* ---------------- ÚTERO / ENDOMÉTRIO / OVÁRIOS ---------------- */
  {o:'utero', nm:/^miometrio/, q:1, cp:'Útero miomatoso.', x:['nódulos'], n:'Mioma', m:'add',
   t:'Nódulo miometrial hipoecogênico XX heterogêneo XX isoecogênico, intramural XX subseroso XX submucoso, na parede XXX, medindo XXX x XXX x XXX cm.',
   c:'Mioma uterino.'},
  {o:'utero', nm:/^miometrio/, x:['nódulos'], n:'Miomas (vários)', m:'add',
   mt:'hipoecogênico XX heterogêneo XX isoecogênico, intramural XX subseroso XX submucoso, na parede XXX, medindo XXX x XXX x XXX cm', mtn:'Nódulo', mtb:'adicionar outro mioma',
   t:'Múltiplos nódulos miometriais, o maior intramural XX subseroso XX submucoso na parede XXX, medindo XXX x XXX x XXX cm.',
   c:'Útero miomatoso.'},
  {o:'utero', nm:/^miometrio/, n:'Adenomiose (padrão)', m:'add',
   t:'Miométrio heterogêneo, com assimetria das paredes, pequenos cistos e estrias ecogênicas.',
   c:'Achados sugestivos de adenomiose.'},
  {o:'utero', n:'Histerectomia', m:'sub',
   t:'não caracterizado (status pós-histerectomia).', c:'Status pós-histerectomia.'},
  {o:'utero', nm:/^miometrio/, n:'Nicho de cesárea', m:'add',
   t:'Falha miometrial em forma de nicho na cicatriz de cesárea, com miométrio residual de XXX cm.',
   c:'Nicho na cicatriz de cesárea (istmocele).'},
  /* miométrio (laudos com item próprio): o mioma reescreve a frase do miométrio */
  {o:'miometrio', n:'Mioma', m:'sub',
   t:'com ecotextura heterogênea, notando-se nódulo hipoecogênico XX heterogêneo XX isoecogênico, intramural XX subseroso XX submucoso, na parede XXX, medindo XXX x XXX x XXX cm.',
   c:'Mioma uterino.'},
  {o:'miometrio', n:'Miomas (vários)', m:'sub',
   mt:'hipoecogênico XX heterogêneo XX isoecogênico, intramural XX subseroso XX submucoso, na parede XXX, medindo XXX x XXX x XXX cm', mtn:'Nódulo', mtb:'adicionar outro mioma',
   t:'com ecotextura heterogênea, notando-se múltiplos nódulos miometriais, o maior intramural XX subseroso XX submucoso na parede XXX, medindo XXX x XXX x XXX cm.',
   c:'Útero miomatoso.'},
  {o:'miometrio', n:'Adenomiose (padrão)', m:'sub',
   t:'heterogêneo, com assimetria das paredes, pequenos cistos e estrias ecogênicas, sem nódulos conspícuos.',
   c:'Achados sugestivos de adenomiose.'},
  {o:'miometrio', n:'Nicho de cesárea', m:'add',
   t:'Falha miometrial em forma de nicho na cicatriz de cesárea, com miométrio residual de XXX cm.',
   c:'Nicho na cicatriz de cesárea (istmocele).'},
  {o:'endometrio', n:'Espessado', m:'sub',
   t:'centrado, espessado e heterogêneo XX homogêneo, medindo XXX mm.',
   c:'Espessamento endometrial ({1} mm).'},
  {o:'endometrio', q:1, cp:'Imagens sugestivas de pólipos endometriais.', n:'Pólipo endometrial', m:'add',
   t:'Imagem ecogênica intracavitária com pedículo vascular ao Doppler, medindo XXX x XXX x XXX cm.', medOpc:1,
   c:'Imagem sugestiva de pólipo endometrial.'},
  {o:'endometrio', n:'Restos ovulares', m:'add',
   t:'Material heterogêneo na cavidade endometrial, medindo XXX x XXX x XXX cm, com fluxo ao Doppler.', medOpc:1,
   c:'Material heterogêneo intracavitário; considerar restos ovulares.'},
  {o:'ovario', q:1, cp:'Cistos ovarianos simples.', n:'Cisto simples', m:'add',
   t:'Cisto simples anecogênico, de paredes finas, medindo XXX x XXX x XXX cm.', medOpc:1,
   c:'Cisto ovariano simples.'},
  {o:'ovario', q:1, cp:'Imagens císticas com aspecto sugestivo de cistos hemorrágicos.', n:'Cisto hemorrágico', m:'add',
   t:'Imagem cística com finos ecos reticulares, sem fluxo interno, medindo XXX x XXX x XXX cm.', medOpc:1,
   c:'Imagem cística com aspecto sugestivo de cisto hemorrágico.'},
  {o:'ovario', n:'Corpo lúteo', m:'add',
   t:'Corpo lúteo com vascularização periférica, medindo XXX x XXX x XXX cm.', medOpc:1, c:''},
  {o:'ovario', n:'Endometrioma', m:'add',
   t:'Imagem cística com conteúdo de ecos finos homogêneos (vidro fosco), medindo XXX x XXX x XXX cm.', medOpc:1,
   c:'Imagem cística com aspecto sugestivo de endometrioma.'},
  {o:'ovario', n:'Padrão micropolicístico', m:'add',
   t:'Múltiplos folículos periféricos (XXX folículos), com estroma ecogênico.',
   c:'Ovário de aspecto micropolicístico.'},
  {o:'ovario', n:'Cisto complexo (O-RADS)', m:'add', kind:'orads',
   t:'medindo XXX x XXX x XXX cm', c:''},
  {o:'ovario', n:'Não caracterizado', m:'sub',
   t:'não caracterizado.', c:''},

  /* ---------------- PARTES MOLES ---------------- */
  {o:'partes', q:1, cp:'Nódulos com aspecto sugestivo de lipomas.', n:'Lipoma', m:'add',
   t:'Nódulo ovalado no subcutâneo, isoecogênico à gordura, com finas estrias, sem fluxo ao Doppler, medindo XXX x XXX cm.',
   c:'Nódulo com aspecto sugestivo de lipoma.'},
  {o:'partes', q:1, cp:'Nódulos com aspecto sugestivo de cistos epidérmicos.', n:'Cisto epidérmico', m:'add',
   t:'Nódulo hipoecogênico bem definido na derme/subcutâneo, com reforço acústico posterior, medindo XXX cm.',
   c:'Nódulo com aspecto sugestivo de cisto epidérmico.'},
  {o:'partes', n:'Coleção / abscesso', m:'add',
   t:'Coleção com conteúdo espesso e debris em XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Coleção em {0}.'},
  {o:'partes', n:'Edema do subcutâneo', m:'add', nm:/^pele e tecido subcutaneo/,
   t:'Espessamento e aumento da ecogenicidade do subcutâneo com faixas líquidas de permeio.',
   c:'Edema do tecido subcutâneo.'},
  {o:'partes', n:'Hematoma', m:'add',
   t:'Coleção heterogênea, sem fluxo ao Doppler, em XXX, medindo XXX x XXX x XXX cm.',
   c:'Coleção com aspecto sugestivo de hematoma.'},

  /* ---------------- TÓRAX ---------------- */
  {o:'pericardio', n:'Derrame pericárdico', m:'sub', vaz:[', com lâmina de até XXX cm'],
   t:'com derrame pericárdico em pequena XX moderada XX grande quantidade, com lâmina de até XXX cm.',
   c:'Derrame pericárdico em {0} quantidade.'},
  {o:'pericardio', n:'Espessamento pericárdico', m:'sub',
   t:'com espessamento pericárdico, sem derrame significativo.',
   c:'Espessamento pericárdico.'},
  {o:'pleura', n:'Derrame pleural', m:'add',
   t:'Derrame pleural à direita XX esquerda, em pequena XX moderada XX grande quantidade, anecogênico.',
   c:'Derrame pleural à {0}.'},
  {o:'pleura', n:'Derrame com atelectasia', m:'add',
   t:'Derrame pleural à direita XX esquerda com atelectasia passiva do parênquima adjacente.',
   c:'Derrame pleural à {0} com atelectasia adjacente.'},
  /* ================= MUSCULOESQUELÉTICO ================= */
  {o:'tendao', n:'Tendinopatia / rotura', m:'sub', kind:'tend', t:'',
   c:''},
  {o:'tendao', n:'Tenossinovite', m:'add', nlb:/cabeca longa do biceps|compartimentos sinoviais extensores|^compartimento (anterior|medial|lateral)/,
   t:'Distensão líquida da bainha do tendão XXX, com espessamento sinovial e hiperemia ao Doppler.',
   c:'Tenossinovite do {0}.'},
  {o:'tendao', n:'Entesopatia', m:'add', nlb:/cabeca longa do biceps|compartimentos sinoviais extensores|^compartimento (anterior|medial|lateral)/, vaz:[' do tendão XXX'],
   t:'Irregularidades corticais e entesófitos na inserção do tendão XXX.',
   c:'Entesopatia do {0}.'},
  {o:'tendao', n:'Distensão líquida da bainha', m:'add', so:['us-ombro'], lb:/cabeca longa do biceps/,
   t:'Distensão líquida da bainha do tendão da cabeça longa do bíceps.',
   c:'Distensão líquida da bainha do tendão da cabeça longa do bíceps.'},
  {o:'tendao', n:'Luxação do bíceps', m:'add', so:['us-ombro'], lb:/cabeca longa do biceps/,
   t:'Tendão da cabeça longa do bíceps fora do sulco intertubercular (luxação medial).',
   c:'Luxação medial do tendão da cabeça longa do bíceps.'},
  /* pele e tecido subcutâneo (US musculoesquelético) */
  /* nódulo com descritores (formato, margens, ecotextura, ecogenicidade, dimensões e distância à pele) */
  {o:'pelesub', n:'Nódulo', m:'add', kind:'nodpm', lugar:'no tecido subcutâneo',
   t:'em XXX, medindo XXX x XXX x XXX cm, distando XXX cm da pele', c:''},
  {o:'partes', n:'Nódulo', m:'add', kind:'nodpm', nlb:/^pele e tecido subcutaneo/,
   t:'em XXX, medindo XXX x XXX x XXX cm, distando XXX cm da pele', c:''},
  {o:'pelesub', n:'Edema', m:'sub',
   t:'com espessamento e aumento da ecogenicidade do tecido subcutâneo, com faixas líquidas de permeio, sem coleções.',
   c:'Edema do tecido subcutâneo.'},
  {o:'pelesub', n:'Celulite', m:'sub',
   t:'com espessamento da pele e do tecido subcutâneo, aumento da ecogenicidade e faixas líquidas de permeio, com aumento da vascularização ao Doppler, sem coleções organizadas.',
   c:'Achados sugestivos de celulite.'},
  {o:'cotfossas', n:'Bursite olecraniana', m:'add', medOpc:1,
   t:'Distensão líquida da bursa olecraniana, com espessamento parietal, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Bursite olecraniana.'},
  {o:'bursa', n:'Bursite', m:'sub', vaz:[', medindo XXX cm de espessura'],
   t:'com distensão líquida e espessamento parietal, medindo XXX cm de espessura.',
   c:'Bursite {L}.'},
  {o:'bursa', so:['us-ombro'], n:'Impacto subacromial (dinâmico)', m:'add',
   t:'Abaulamento da bursa sob o acrômio durante a abdução do braço, com limitação do deslizamento tendíneo.',
   c:'Sinais de impacto subacromial à manobra dinâmica.'},
  {o:'derrame', n:'Derrame articular', m:'sub',
   t:'presente, em pequena XX moderada XX grande quantidade.',
   c:'Derrame articular ({0} quantidade).'},
  {o:'derrame', n:'Derrame com sinovite', m:'sub',
   t:'presente, com espessamento sinovial e debris, em pequena XX moderada XX grande quantidade, com hiperemia sinovial ao Doppler.',
   c:'Derrame articular com espessamento sinovial (sinovite).'},
  {o:'acromio', n:'Artropatia degenerativa', m:'sub',
   t:'com irregularidades corticais, osteófitos e distensão capsular.',
   c:'Artropatia degenerativa acromioclavicular.'},
  {o:'poplitea', n:'Cisto de Baker', m:'sub',
   t:'com formação cística entre o gastrocnêmio medial e o semimembranoso, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Cisto de Baker.'},
  {o:'poplitea', n:'Cisto de Baker roto', m:'sub',
   t:'com formação cística entre o gastrocnêmio medial e o semimembranoso, de contornos afilados inferiormente, com líquido dissecando os planos da panturrilha, medindo XXX cm.',
   c:'Cisto de Baker com sinais de rotura.'},
  {o:'poplitea', n:'TVP da veia poplítea', m:'add',
   t:'Veia poplítea aumentada de calibre e não compressível, com material ecogênico intraluminal oclusivo XX suboclusivo, compatível com trombose venosa profunda.',
   c:'Trombose venosa profunda da veia poplítea.'},
  {o:'poplitea', n:'Aneurisma da artéria poplítea', m:'add', vaz:[' e extensão de XXX cm'],
   t:'Dilatação aneurismática fusiforme XX sacular da artéria poplítea, com diâmetro máximo de XXX cm e extensão de XXX cm, sem XX com trombo mural.',
   c:'Aneurisma {0} da artéria poplítea.'},
  {o:'ligamento', n:'Estiramento / rotura', m:'sub', kind:'lig', t:'', c:''},
  {o:'ligamento', so:['us-joelho'], n:'Calcificação (Pellegrini-Stieda)', m:'add',
   t:'Calcificação junto à origem femoral do ligamento colateral medial.',
   c:'Calcificação de Pellegrini-Stieda.'},
  {o:'fascia', n:'Fascite plantar', m:'sub',
   t:'espessada (XXX cm junto à inserção calcânea) e hipoecogênica.',
   c:'Fascite plantar.'},
  {o:'fascia', n:'Fibromatose plantar', m:'add',
   t:'Nódulo fusiforme hipoecogênico na fáscia plantar, medindo XXX cm.',
   c:'Nódulo na fáscia plantar sugestivo de fibromatose plantar.'},
  {o:'nervo', n:'Túnel do carpo', m:'sub',
   t:'espessado e hipoecogênico na entrada do túnel do carpo, com área seccional de XXX mm².',
   c:'Espessamento do nervo mediano no túnel do carpo, compatível com neuropatia compressiva, a correlacionar clinicamente.'},
  {o:'nervo', n:'Neuropatia ulnar', m:'sub',
   t:'espessado e hipoecogênico no túnel cubital, com área seccional de XXX mm².',
   c:'Espessamento do nervo ulnar no cotovelo, compatível com neuropatia compressiva.'},
  {o:'nervo', n:'Subluxação do ulnar', m:'add',
   t:'Subluxação anterior do nervo ulnar sobre o epicôndilo medial à flexão do cotovelo.',
   c:'Instabilidade (subluxação) do nervo ulnar.'},
  {o:'musculo', n:'Lesão muscular', m:'sub', kind:'musc', t:'',
   c:''},
  /* punho: cisto gangliônico (artrossinovial) e cisto peritendíneo, com articulação e face */
  {o:'partes', so:['us-punho'], q:1, n:'Cisto gangliônico (artrossinovial)', m:'add', medOpc:1,
   cp:'Cistos gangliônicos (artrossinoviais) no punho.',
   t:'Formação cística anecogênica, de paredes finas, sem fluxo ao Doppler, junto à articulação radiocárpica XX ulnocárpica XX intercárpica XX carpometacarpal, na face anterior XX posterior XX radial XX ulnar do punho, medindo XXX x XXX x XXX cm, compatível com cisto gangliônico (artrossinovial).',
   c:'Cisto gangliônico (artrossinovial) junto à articulação {0}, na face {1} do punho.'},
  {o:'partes', so:['us-punho'], q:1, n:'Cisto peritendíneo', m:'add', medOpc:1, vaz:[' (tendão XXX)'],
   cp:'Cistos peritendíneos no punho.',
   t:'Formação cística anecogênica, de paredes finas, sem fluxo ao Doppler, adjacente à bainha tendínea (tendão XXX), na face anterior XX posterior XX radial XX ulnar do punho, medindo XXX x XXX x XXX cm, compatível com cisto peritendíneo.',
   c:'Cisto peritendíneo na face {1} do punho.'},
  {o:'partes', nso:['us-punho'], n:'Cisto sinovial (gânglio)', m:'add',
   t:'Formação cística anecogênica, lobulada, junto a XXX, medindo XXX cm, sem fluxo ao Doppler.',
   c:'Cisto sinovial (gânglio).'},
  {o:'interdigital', n:'Neuroma de Morton', m:'sub',
   t:'com nódulo hipoecogênico no XXX espaço intermetatarsal, medindo XXX cm.',
   c:'Nódulo no {0} espaço intermetatarsal sugestivo de neuroma de Morton.'},
  /* parede abdominal: hérnias com descritores (colo, saco herniário, conteúdo) */
  {o:'hernia', so:['us-parede-abdominal'], n:'Hérnia supraumbilical', m:'add', kind:'hernia', ht:'supraumbilical',
   t:'Colo: XXX x XXX cm. Saco herniário: XXX x XXX x XXX cm. Distância da cicatriz umbilical: XXX cm.', c:''},
  {o:'hernia', so:['us-parede-abdominal'], n:'Hérnia umbilical', m:'add', kind:'hernia', ht:'umbilical',
   t:'Colo: XXX x XXX cm. Saco herniário: XXX x XXX x XXX cm.', c:''},
  {o:'hernia', so:['us-parede-abdominal'], n:'Hérnia incisional', m:'add', kind:'hernia', ht:'incisional',
   t:'Colo: XXX x XXX cm. Saco herniário: XXX x XXX x XXX cm.', c:''},
  /* parede abdominal: planos musculares */
  {o:'musculo', so:['us-parede-abdominal'], n:'Distância inter-retos (diástase)', m:'sub', retos:1,
   t:'com arquitetura preservada; distância entre os músculos retos abdominais de XXX cm, na região epigástrica XX mesogástrica XX hipogástrica.', c:''},
  {o:'musculo', so:['us-partes-moles'], q:1, n:'Lipoma intramuscular', m:'add', medOpc:1, vaz:[', em XXX'],
   cp:'Lesões com aspecto sugestivo de lipomas intramusculares.',
   t:'Formação ovalada, isoecogênica XX hiperecogênica ao tecido adiposo, homogênea, de limites bem definidos, sem fluxo ao Doppler, no interior do plano muscular, em XXX, medindo XXX x XXX x XXX cm, distando XXX cm da pele, com aspecto sugestivo de lipoma.',
   c:'Lesão no plano muscular com aspecto sugestivo de lipoma.'},
  {o:'musculo', so:['us-parede-abdominal'], n:'Lipossubstituição', m:'add',
   t:'Sinais de lipossubstituição dos planos musculares.', c:'Lipossubstituição dos planos musculares da parede abdominal.'},
  /* partes moles / parede abdominal: coleções */
  {o:'partes', so:['us-partes-moles','us-parede-abdominal'], n:'Coleção organizada', m:'sub', medOpc:1,
   t:'coleção organizada, de paredes definidas e conteúdo espesso com debris, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³), distando XXX cm da pele.',
   c:'Coleção organizada.'},
  {o:'partes', so:['us-partes-moles','us-parede-abdominal'], n:'Coleção não organizada', m:'sub', medOpc:1,
   t:'coleção não organizada, sem paredes definidas, com conteúdo líquido heterogêneo, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³), distando XXX cm da pele.',
   c:'Coleção não organizada.'},
  /* região inguinal: canal inguinal */
  {o:'canalinguinal', n:'Hérnia inguinoescrotal', m:'sub', medOpc:1,
   t:'com hérnia inguinoescrotal à direita XX esquerda, com colo medindo XXX cm, contendo gordura XX intestino, que se insinua até a bolsa testicular.',
   c:'Hérnia inguinoescrotal à {0}.'},
  {o:'hernia', n:'Hérnia inguinal', m:'sub',
   t:'hérnia inguinal direta XX indireta à direita XX esquerda, com colo de XXX cm, contendo gordura XX intestino, redutível XX irredutível.',
   c:'Hérnia inguinal {0} à {1}.'},

  /* ================= DOPPLER VASCULAR ================= */
  {o:'carotida', n:'Espessamento médio-intimal', m:'sub',
   t:'espessados, medindo até XXX cm à direita e XXX cm à esquerda.',
   c:'Espessamento médio-intimal carotídeo.'},
  {o:'carotida', n:'Placa sem estenose significativa', m:'add', x:['espessamentos','calcificações','calcificações parietais'],
   t:'Placa ateromatosa calcificada XX hipoecogênica XX mista na bifurcação XX origem da carótida interna direita XX esquerda, com espessura de XXX cm, sem estenose hemodinamicamente significativa.',
   c:'Ateromatose carotídea sem estenose hemodinamicamente significativa.'},
  {o:'carotida', n:'Estenose da carótida interna', m:'add', x:['espessamentos','calcificações','calcificações parietais'],
   t:'Placa na carótida interna direita XX esquerda determinando estenose, com VPS de XXX cm/s, VDF de XXX cm/s e relação VPS ACI/ACC de XXX, estimada em XXX %.',
   c:'Estenose da carótida interna {0} estimada em {4}%.'},
  {o:'carotida', n:'Oclusão da carótida interna', m:'add',
   t:'Ausência de fluxo na carótida interna direita XX esquerda, com padrão de alta resistência na carótida comum ipsilateral.',
   c:'Oclusão da carótida interna {0}.'},
  {o:'carotida', n:'Acotovelamento (kinking)', m:'add',
   t:'Acotovelamento da carótida interna direita XX esquerda, sem aceleração significativa do fluxo.',
   c:'Acotovelamento (kinking) da carótida interna {0}.'},
  {o:'vertebral', n:'Roubo da subclávia', m:'sub',
   t:'artéria vertebral direita XX esquerda com fluxo invertido XX alternante (bidirecional); contralateral com fluxo anterógrado.',
   c:'Fluxo {1} na artéria vertebral {0}, sugestivo de roubo da subclávia.'},
  {o:'vertebral', n:'Hipoplasia', m:'sub',
   t:'com fluxo anterógrado; artéria vertebral direita XX esquerda de calibre reduzido (XXX cm).',
   c:'Hipoplasia da artéria vertebral {0}.'},
  {o:'vertebral', n:'Sem fluxo', m:'sub',
   t:'artéria vertebral direita XX esquerda sem fluxo detectável; contralateral com fluxo anterógrado.',
   c:'Ausência de fluxo na artéria vertebral {0} (oclusão?).'},
  {o:'arterial', n:'Ateromatose sem estenose', m:'add', x:['placas'],
   t:'Placas ateromatosas parietais esparsas, sem estenoses hemodinamicamente significativas.',
   c:'Ateromatose sem estenoses hemodinamicamente significativas.'},
  {o:'arterial', n:'Estenose', m:'add', x:['placas'],
   t:'Exceto na artéria XXX, onde há placa determinando aceleração focal do fluxo (VPS de XXX cm/s; razão de VPS de XXX), compatível com estenose acima XX abaixo de 50%.',
   c:'Estenose {3} de 50% na artéria {0}.'},
  {o:'arterial', n:'Oclusão', m:'add',
   t:'Exceto a artéria XXX, ocluída em extensão de XXX cm, com reenchimento distal por colaterais e fluxo monofásico a jusante.',
   c:'Oclusão da artéria {0}.'},
  {o:'arterial', n:'Aneurisma poplíteo', m:'add',
   t:'Dilatação aneurismática da artéria poplítea direita XX esquerda, medindo XXX cm, com trombo mural.',
   c:'Aneurisma da artéria poplítea {0}.'},
  {o:'arterial', n:'Fluxo monofásico distal', m:'add',
   t:'Fluxo monofásico de baixa amplitude nas artérias distais, sugerindo doença obstrutiva proximal.',
   c:'Padrão monofásico distal, sugerindo doença obstrutiva proximal.'},
  {o:'iliaca', n:'Estenose ilíaca', m:'add',
   t:'Exceto na artéria ilíaca XXX direita XX esquerda, com aceleração focal do fluxo (VPS de XXX cm/s; razão de VPS de XXX).',
   c:'Sinais de estenose da artéria ilíaca {0} {1}.'},
  {o:'iliaca', n:'Aneurisma ilíaco', m:'add',
   t:'Dilatação aneurismática da artéria ilíaca XXX direita XX esquerda, medindo XXX cm.',
   c:'Aneurisma da artéria ilíaca {0} {1}.'},
  {o:'venoso', n:'TVP aguda', m:'add', x:['tromboses'],
   t:'Exceto a veia XXX direita XX esquerda, que se apresenta com calibre aumentado, incompressível e preenchida por trombo hipoecogênico, com ausência XX presença parcial de fluxo ao Doppler.',
   c:'Trombose venosa profunda de aspecto agudo na veia {0} {1}.'},
  {o:'venoso', n:'TVP crônica', m:'add', x:['tromboses'],
   t:'Exceto a veia XXX direita XX esquerda, com paredes espessadas, trombo ecogênico parcialmente aderido e recanalização parcial.',
   c:'Sinais de trombose venosa profunda crônica, com recanalização parcial, na veia {0} {1}.'},
  {o:'venoso', n:'Trombose de veias musculares', m:'add',
   t:'Veias gastrocnêmias XX soleares da perna direita XX esquerda com trombos, incompressíveis.',
   c:'Trombose de veias musculares da panturrilha {1}.'},
  {o:'venoso', n:'Tromboflebite superficial', m:'add',
   t:'Veia superficial XXX com trombo intraluminal, incompressível, com sinais inflamatórios no subcutâneo adjacente.',
   c:'Tromboflebite superficial da veia {0}.'},
  {o:'varizes', n:'Junção safeno-femoral incompetente', m:'sub',
   t:'Junção safeno-femoral direita XX esquerda incompetente, com refluxo de XXX s à manobra de Valsalva.',
   c:'Incompetência da junção safeno-femoral {0}.'},
  {o:'varizes', n:'Safena magna com refluxo', m:'sub',
   t:'Veia safena magna direita XX esquerda pérvia, com refluxo desde XXX até XXX; demais safenas sem refluxo.',
   c:'Insuficiência da veia safena magna {0}.'},
  {o:'varizes', n:'Safena parva com refluxo', m:'sub',
   t:'Veia safena parva direita XX esquerda pérvia, com refluxo desde XXX até XXX; demais safenas sem refluxo.',
   c:'Insuficiência da veia safena parva {0}.'},
  {o:'varizes', n:'Perfurante incompetente', m:'sub',
   t:'Veia perfurante incompetente na face medial XX posterior XX lateral da perna direita XX esquerda, a cerca de XXX cm da planta do pé, com calibre de XXX cm.',
   c:'Veia perfurante incompetente na perna {1}.'},
  {o:'varizes', n:'Varicosidades', m:'add',
   t:'Varicosidades no subcutâneo da face XXX da perna XX coxa direita XX esquerda.',
   c:'Varicosidades no membro inferior {2}.'},
  {o:'renalart', n:'Estenose da artéria renal', m:'sub',
   t:'pérvias, com aceleração focal do fluxo no segmento XXX da artéria renal direita XX esquerda (VPS de XXX cm/s; relação renal-aórtica de XXX).',
   c:'Sinais hemodinâmicos de estenose da artéria renal {1}.'},
  {o:'renalart', n:'Padrão tardus-parvus', m:'sub',
   t:'com padrão tardus-parvus à direita XX esquerda (tempo de aceleração de XXX ms; IR de XXX).',
   c:'Padrão tardus-parvus intrarrenal à {0}, sugerindo estenose proximal.'},
  {o:'renalart', n:'IR aumentado', m:'sub',
   t:'com índices de resistência aumentados (até XXX) à direita XX esquerda XX bilateralmente.',
   c:'Aumento dos índices de resistência intrarrenais.'},
  {o:'temporal', n:'Sinal do halo', m:'sub',
   t:'pérvias, com halo hipoecogênico parietal circunferencial, não compressível, de XXX mm de espessura no ramo XXX direito XX esquerdo.',
   c:'Sinal do halo em artéria temporal superficial, sugestivo de arterite de células gigantes, a correlacionar clinicamente.'},
  {o:'veiafav', n:'Calibre reduzido', m:'sub',
   t:'pérvia, de calibre reduzido (XXX cm no XXX).',
   c:'Veia {L} de calibre reduzido.'},
  {o:'veiafav', n:'Trombose / esclerose', m:'sub',
   t:'com paredes espessadas e trombo no segmento XXX, não compressível.',
   c:'Trombose da veia {L} no segmento {0}.'},
  /* ================= MAMA (léxico ACR BI-RADS US) ================= */
  {o:'mama', q:1, n:'Nódulo sólido (BI-RADS)', m:'add', kind:'birads', x:['nódulos','císticos'],
   t:'às XXX horas, a XXX cm do mamilo, a XXX cm da pele, medindo XXX x XXX x XXX cm'},
  {o:'mama', q:1, cp:'Cistos simples na {L} (BI-RADS® 2).', n:'Cisto simples', m:'add', br:'2', x:['nódulos','císticos'],
   t:'Cisto simples (anecoico, circunscrito, com reforço acústico posterior), às XXX horas, medindo XXX x XXX x XXX cm.', medOpc:1, loct:'às XXX horas, medindo XXX x XXX x XXX cm',
   tn:'Cistos simples (anecoicos, circunscritos, com reforço acústico posterior), o maior às XXX horas, medindo XXX x XXX x XXX cm.',
   c:'Cisto simples na {L} (BI-RADS® 2).'},
  {o:'mama', n:'Microcistos agrupados', m:'add', br:'2', x:['nódulos','císticos'],
   t:'Agrupamento de microcistos com finas septações, sem componente sólido, às XXX horas, medindo XXX cm no conjunto.',
   c:'Microcistos agrupados na {L} (BI-RADS® 2).'},
  {o:'mama', q:1, cp:'Cistos de conteúdo espesso na {L} (BI-RADS® 2).', n:'Cisto de conteúdo espesso', m:'add', br:'2', x:['nódulos','císticos'],
   t:'Cisto de conteúdo espesso (circunscrito, com ecos internos homogêneos de baixa amplitude, sem componente sólido nem fluxo ao Doppler), às XXX horas, medindo XXX x XXX x XXX cm.', medOpc:1, loct:'às XXX horas, medindo XXX x XXX x XXX cm',
   tn:'Cistos de conteúdo espesso (circunscritos, com ecos internos homogêneos de baixa amplitude, sem componente sólido nem fluxo ao Doppler), o maior às XXX horas, medindo XXX x XXX x XXX cm.',
   c:'Cisto de conteúdo espesso na {L} (BI-RADS® 2).'},
  {o:'mama', n:'Massa complexa cística e sólida', m:'add', br:'4', x:['nódulos','císticos'],
   t:'Massa complexa com componentes cístico e sólido, com fluxo no componente sólido, às XXX horas, a XXX cm do mamilo, a XXX cm da pele, medindo XXX x XXX x XXX cm.',
   c:'Massa complexa cística e sólida na {L} (BI-RADS® 4 — recomenda-se estudo histopatológico).'},
  {o:'mama', n:'Distorção arquitetural', m:'add', br:'4', x:['distorção'],
   t:'Área de distorção arquitetural às XXX horas, a XXX cm do mamilo, a XXX cm da pele, medindo XXX cm, sem nódulo definido.',
   c:'Distorção arquitetural na {L} (BI-RADS® 4 — recomenda-se estudo histopatológico; correlacionar com mamografia).'},
  {o:'mama', q:1, cp:'Linfonodos intramamários (BI-RADS® 2).', n:'Linfonodo intramamário', m:'add', br:'2',
   t:'Linfonodo intramamário de aspecto habitual, com hilo adiposo, às XXX horas, medindo XXX cm.',
   c:'Linfonodo intramamário (BI-RADS® 2).'},
  {o:'mama', q:1, cp:'Cistos oleosos na {L} (BI-RADS® 2).', n:'Cisto oleoso / esteatonecrose', m:'add', br:'2', x:['nódulos','císticos'],
   t:'Imagem circunscrita com conteúdo ecogênico e nível, às XXX horas, medindo XXX cm, compatível com cisto oleoso (esteatonecrose).',
   c:'Cisto oleoso na {L} (BI-RADS® 2).'},
  {o:'mama', n:'Alterações pós-cirúrgicas', m:'add', br:'2',
   t:'Alterações cicatriciais na região XXX, compatíveis com manipulação cirúrgica prévia, sem lesões nodulares associadas.',
   c:'Alterações pós-cirúrgicas na {L} (BI-RADS® 2).'},
  {o:'mama', n:'Espessamento cutâneo / edema', m:'add',
   t:'Espessamento cutâneo (XXX cm) e edema do tecido subcutâneo.',
   c:'Espessamento cutâneo e edema na {L}.'},
  {o:'mama', n:'Coleção / abscesso', m:'add',
   t:'Coleção com conteúdo espesso e debris às XXX horas, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³), com edema dos tecidos adjacentes.',
   c:'Coleção na {L}, sugestiva de abscesso, a correlacionar clinicamente.'},
  {o:'mama', n:'Implante íntegro', m:'add',
   t:'Implante mamário de contornos regulares, sem sinais de rotura.',
   c:''},
  {o:'mama', n:'Rotura intracapsular', m:'add',
   t:'Implante com linhas ecogênicas paralelas em seu interior (sinal da escada), sugerindo rotura intracapsular.',
   c:'Sinais de rotura intracapsular do implante na {L}.'},
  {o:'mama', n:'Rotura extracapsular', m:'add',
   t:'Área hiperecogênica com sombra acústica difusa (padrão em tempestade de neve) junto ao implante, compatível com silicone livre.',
   c:'Sinais de rotura extracapsular do implante na {L}.'},
  {o:'mama', n:'Mastectomia', m:'sub',
   t:'não caracterizada (status pós-mastectomia); plastrão sem lesões nodulares.',
   c:'Status pós-mastectomia ({L}).'},
  {o:'mama', n:'Ginecomastia', m:'sub',
   t:'com tecido fibroglandular retroareolar de padrão nodular XX dendrítico XX difuso, medindo XXX cm de espessura.',
   c:'Ginecomastia ({L}).'},
  {o:'ductos', n:'Ectasia ductal', m:'sub',
   t:'ductos retroareolares ectasiados à direita XX à esquerda XX bilateralmente, medindo até XXX cm, com conteúdo anecoico XX ecogênico.',
   c:'Ectasia ductal retroareolar.'},
  {o:'ductos', n:'Lesão intraductal', m:'add', br:'4', x:['lesões intraductais'],
   t:'Imagem sólida intraductal na região XXX da mama direita XX esquerda, medindo XXX cm, com fluxo ao Doppler.',
   c:'Lesão sólida intraductal na mama {1} (BI-RADS® 4 — recomenda-se estudo histopatológico).'},
  {o:'axila', n:'Linfonodo atípico', m:'sub',
   t:'linfonodo axilar direito XX esquerdo com espessamento cortical (XXX cm) e hilo adiposo reduzido XX ausente, medindo XXX cm; demais de aspecto habitual.',
   c:'Linfonodo axilar {0} de aspecto atípico — correlação clínica e prosseguimento da investigação.'},
  {o:'axila', n:'Linfonodos reacionais', m:'sub',
   t:'linfonodos de aspecto reacional, com cortical discretamente espessada e hilo adiposo preservado, o maior medindo XXX cm.',
   c:''},
  {o:'axila', n:'Tecido mamário acessório', m:'add',
   t:'Tecido fibroglandular acessório na axila direita XX esquerda.',
   c:'Tecido mamário acessório axilar.'},
  /* ================= COMPARAÇÃO COM EXAME PRÉVIO ================= */
  {o:'comparacao', n:'Estabilidade', m:'sub',
   t:'em relação ao exame prévio de XXX, nota-se estabilidade dos achados.',
   c:'Estabilidade dos achados em relação ao exame de {0}.'},
  {o:'comparacao', n:'Alterações', m:'sub',
   t:'em relação ao exame prévio de XXX, notam-se as seguintes alterações: XXX.',
   c:'Alterações em relação ao exame de {0}: {1}.'},
  {o:'comparacao', n:'Estabilidade + achado novo', m:'sub',
   t:'em relação ao exame prévio de XXX, nota-se estabilidade dos achados descritos anteriormente, com surgimento de: XXX.',
   c:'Achado novo em relação ao exame de {0}: {1}.'},
  {o:'comparacao', n:'Exame prévio sem achados', m:'sub',
   t:'em relação ao exame prévio de XXX, que não apresentava alterações, notam-se: XXX.',
   c:'Achados novos em relação ao exame de {0}.'},
  /* ================= MAMOGRAFIA (léxico ACR BI-RADS® mamografia) =================
     loc 1 = escolha de quadrante/terço; {LOC} marca onde entra no texto.
     medOpc 1 = medidas opcionais (em branco, saem do texto). */
  {o:'mgmama', q:1, n:'Nódulo (BI-RADS)', m:'add', kind:'mgnod', loc:1,
   t:'a XXX cm do mamilo, medindo XXX x XXX cm'},
  {o:'mgmama', n:'Calcificações (BI-RADS)', m:'add', kind:'mgcalc', loc:1, medOpc:1,
   t:'ocupando área de XXX x XXX cm'},
  {o:'mgmama', n:'Assimetria', m:'add', kind:'mgass', loc:1, medOpc:1,
   t:'medindo XXX cm'},
  {o:'mgmama', n:'Distorção arquitetural', m:'add', kind:'mgdist', loc:1, medOpc:1,
   t:'medindo XXX cm'},
  {o:'mgmama', n:'Calcificações benignas esparsas', m:'add', br:'2',
   t:'Calcificações esparsas de aspecto tipicamente benigno.',
   c:'Calcificações de aspecto benigno na {L} (BI-RADS® 2).'},
  {o:'mgmama', n:'Calcificações vasculares', m:'add', br:'2',
   t:'Calcificações vasculares de trajeto tubular.',
   c:'Calcificações vasculares na {L} (BI-RADS® 2).'},
  {o:'mgmama', q:1, cp:'Linfonodos intramamários na {L} (BI-RADS® 2).', n:'Linfonodo intramamário', m:'add', br:'2', loc:1, medOpc:1,
   t:'Linfonodo intramamário de aspecto habitual, reniforme e com hilo adiposo, {LOC}, medindo XXX cm.',
   c:'Linfonodo intramamário na {L} (BI-RADS® 2).'},
  {o:'mgmama', q:1, cp:'Fibroadenomas calcificados na {L} (BI-RADS® 2).', n:'Fibroadenoma calcificado', m:'add', br:'2', loc:1, medOpc:1, x:['nódulos'],
   t:'Nódulo com calcificações grosseiras ("em pipoca") {LOC}, medindo XXX cm, compatível com fibroadenoma em involução.',
   c:'Fibroadenoma calcificado na {L} (BI-RADS® 2).'},
  {o:'mgmama', n:'Lesão com conteúdo de gordura', m:'add', br:'2', loc:1, medOpc:1,
   t:'Nódulo circunscrito com conteúdo de densidade de gordura {LOC}, medindo XXX cm, compatível com lipoma XX hamartoma XX esteatonecrose.',
   c:'Lesão com conteúdo de gordura na {L}, compatível com {1} (BI-RADS® 2).'},
  {o:'mgmama', n:'Alterações pós-cirúrgicas', m:'add', br:'2', loc:1,
   t:'Alterações cicatriciais no sítio cirúrgico {LOC}, sem nódulos ou calcificações suspeitas associados.',
   c:'Alterações pós-cirúrgicas na {L} (BI-RADS® 2).'},
  {o:'mgmama', n:'Clipe metálico', m:'add', loc:1,
   t:'Clipe metálico {LOC}, marcando o sítio de biópsia prévia.',
   c:'Clipe metálico de biópsia prévia na {L}.'},
  {o:'mgmama', n:'Mastectomia', m:'sub',
   t:'não caracterizada (status pós-mastectomia).',
   c:'Status pós-mastectomia ({L}).'},
  {o:'mgmama', n:'Ginecomastia', m:'sub', br:'2',
   t:'com tecido fibroglandular retroareolar de padrão nodular XX dendrítico XX difuso.',
   c:'Ginecomastia na {L} (BI-RADS® 2).'},
  {o:'mgpele', n:'Espessamento cutâneo', m:'add', medOpc:1, x:['pele de espessura preservada'],
   t:'Espessamento cutâneo na mama direita XX esquerda, medindo XXX cm.',
   c:'Espessamento cutâneo na mama {0}.'},
  {o:'mgpele', n:'Edema / trabeculado espessado', m:'add', x:['pele de espessura preservada'],
   t:'Espessamento da pele e do trabeculado na mama direita XX esquerda, sugerindo edema.',
   c:'Sinais de edema na mama {0}, a correlacionar com os dados clínicos.'},
  {o:'mgpele', n:'Retração cutânea', m:'add',
   t:'Retração cutânea na mama direita XX esquerda.',
   c:'Retração cutânea na mama {0}.'},
  {o:'mgpele', n:'Retração do mamilo', m:'add',
   t:'Retração do mamilo direito XX esquerdo.',
   c:'Retração do mamilo {0}.'},
  {o:'mgpele', n:'Calcificações cutâneas', m:'add', br:'2',
   t:'Calcificações cutâneas de aspecto benigno.',
   c:'Calcificações cutâneas (BI-RADS® 2).'},
  {o:'mgaxila', n:'Linfonodo atípico', m:'sub', medOpc:1,
   t:'linfonodo axilar direito XX esquerdo denso, arredondado e sem hilo adiposo caracterizável, medindo XXX cm; demais de aspecto habitual.',
   c:'Linfonodo axilar {0} de aspecto atípico — correlação clínica e complementação com ultrassonografia.'},
  {o:'mgaxila', n:'Linfonodos proeminentes (reacionais)', m:'sub', br:'2', medOpc:1,
   t:'linfonodos proeminentes, com hilo adiposo preservado (o maior medindo XXX cm).',
   c:'Linfonodos axilares proeminentes, de aspecto reacional (BI-RADS® 2).'},
  {o:'mgaxila', n:'Tecido mamário acessório', m:'add', br:'2',
   t:'Tecido fibroglandular acessório na axila direita XX esquerda.',
   c:'Tecido mamário acessório axilar (BI-RADS® 2).'},
  {o:'mgmama', n:'Calcificações capsulares (implante)', m:'add', br:'2',
   t:'Calcificações capsulares periprotéticas.',
   c:'Calcificações capsulares periprotéticas (BI-RADS® 2).'},
];

/* mamografia: órgãos próprios (o léxico é outro) */
const LAU_FRASE_ORGAOS_MMG = [
  ['mgmama', /^mama\b/],
  ['mgpele', /^pele|areolopapilar/],
  ['mgaxila', /axila/],
  ['comparacao', /^comparac/],
];
function lauFraseOrgao(label, metodo){
  const n = String(label||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  if(metodo==='dmo') return [];
  if(metodo==='tcg') return typeof LAU_FRASE_ORGAOS_TC!=='undefined' ? LAU_FRASE_ORGAOS_TC.filter(o=>o[1].test(n)).map(o=>o[0]) : [];   // TC (exceto OCT)
  if(metodo==='tc' && typeof LAU_FRASE_ORGAOS_OCT!=='undefined') return LAU_FRASE_ORGAOS_OCT.filter(o=>o[1].test(n)).map(o=>o[0]);
  return (metodo==='mmg' ? LAU_FRASE_ORGAOS_MMG : LAU_FRASE_ORGAOS).filter(o=>o[1].test(n)).map(o=>o[0]);
}
function lauFrasesDe(orgs){
  orgs = [].concat(orgs||[]);
  return LAU_FRASES.map((f,i)=>Object.assign({i},f)).filter(f=>orgs.indexOf(f.o)>=0);
}
