/* =========================================================================
   KlugRads — Biblioteca de frases de alteração (laudos de US)
   ---------------------------------------------------------------------------
   Redação própria do KlugRads. Temas organizados com base no laudário de
   referência enviado pelo usuário e no compêndio indicado (apenas como guia
   do que costuma ser descrito; o texto não foi copiado).

   Campos:
     o  órgão (chave de LAU_FRASE_ORGAOS)
     n  nome no botão
     m  'sub' substitui o texto do item | 'add' acrescenta uma linha
     t  texto do laudo — XXX = campo; "a XX b" = escolha
     c  conclusão; {0}, {1}… = valor do campo/escolha nº 0, 1… do texto
   ========================================================================= */

/* rótulo do item (normalizado, sem acento) → órgão da biblioteca */
const LAU_FRASE_ORGAOS = [
  ['figado', /^figado/],
  ['porta', /veias? porta|porta e hepat/],
  ['vesicula', /^vesicula biliar/],
  ['vias', /^vias biliares/],
  ['pancreas', /^pancreas/],
  ['baco', /^baco/],
  ['rins', /^rins?\b|^rim /],
  ['bexiga', /^bexiga/],
  ['prostata', /^prostata/],
  ['aorta', /^aorta/],
  ['peritoneo', /^peritoneo/],
  ['tireoide', /^tireoide|^lobo (direito|esquerdo)|^istmo/],
  ['linfonodos', /linfonod/],
  ['salivares', /parotida|submandibular|glandulas? salivar/],
  ['testiculo', /testicul|^bolsa|^epididimo/],
  ['utero', /^utero|^miometrio/],
  ['endometrio', /^endometrio/],
  ['ovario', /^ovario/],
  ['partes', /formac|massas|^coleco|tecido|subcutane|^pele|^musculatura|^musculo/],
  ['pleura', /pleura|cupula|hemitorax/],
  ['__extra', /^__extra$/],
];

const LAU_FRASES = [
  /* ---------------- FÍGADO ---------------- */
  {o:'figado', s:1, n:'Hepatomegalia', m:'sub',
   t:'com dimensões aumentadas (lobo direito medindo XXX cm), contornos regulares e bordas finas. Ecotextura parenquimatosa hepática homogênea.',
   c:'Hepatomegalia homogênea.'},
  {o:'figado', s:1, n:'Esteatose', m:'sub',
   t:'com dimensões normais, contornos regulares e bordas finas. Ecogenicidade parenquimatosa difusamente aumentada, de grau leve XX moderado XX acentuado.',
   c:'Esteatose hepática de grau {0}.'},
  {o:'figado', n:'Esteatose com área de preservação', m:'add',
   t:'Área hipoecogênica mal definida no segmento XXX, medindo XXX cm, compatível com área de parênquima poupado pela infiltração gordurosa.',
   c:'Área focal de preservação gordurosa no segmento {0}.'},
  {o:'figado', s:1, n:'Hepatopatia crônica', m:'sub',
   t:'com contornos lobulados, bordas rombas e lobo caudado proeminente. Ecotextura parenquimatosa difusamente heterogênea e grosseira.',
   c:'Sinais ultrassonográficos de hepatopatia crônica.'},
  {o:'figado', n:'Fibrose periportal', m:'sub',
   t:'com contornos discretamente irregulares e aumento da ecogenicidade periportal difusa, com espessamento das paredes dos ramos portais.',
   c:'Sinais de fibrose periportal (correlacionar com esquistossomose).'},
  {o:'figado', n:'Hepatite aguda (padrão)', m:'add',
   t:'Discreto aumento da ecogenicidade das paredes dos ramos portais, em contraste com parênquima de ecogenicidade reduzida.',
   c:'Alteração parenquimatosa hepática difusa, que pode estar relacionada a hepatite aguda, a critério clínico-laboratorial.'},
  {o:'figado', s:1, n:'Cisto simples', m:'add',
   t:'Imagem cística de paredes finas, conteúdo anecogênico e reforço acústico posterior no segmento XXX, medindo XXX cm.',
   c:'Cisto hepático simples.'},
  {o:'figado', s:1, n:'Cistos simples (vários)', m:'add',
   t:'Imagens císticas simples esparsas pelo parênquima, a maior no segmento XXX, medindo XXX cm.',
   c:'Cistos hepáticos simples.'},
  {o:'figado', s:1, n:'Hemangioma', m:'add',
   t:'Nódulo hiperecogênico, homogêneo, de contornos bem definidos, sem sombra acústica, no segmento XXX, medindo XXX cm.',
   c:'Nódulo hepático com aspecto sugestivo de hemangioma.'},
  {o:'figado', s:1, n:'Calcificação', m:'add',
   t:'Foco hiperecogênico com sombra acústica posterior no segmento XXX, medindo XXX cm.',
   c:'Calcificação hepática de aspecto residual.'},
  {o:'figado', s:1, n:'Nódulo sólido indeterminado', m:'add',
   t:'Nódulo sólido hipoecogênico XX hiperecogênico XX heterogêneo no segmento XXX, medindo XXX cm.',
   c:'Nódulo hepático sólido indeterminado. Sugere-se complementação com TC ou RM com contraste.'},
  {o:'figado', n:'Nódulos com halo (secundário?)', m:'add',
   t:'Múltiplos nódulos sólidos com halo hipoecogênico, esparsos pelo parênquima, o maior no segmento XXX, medindo XXX cm.',
   c:'Múltiplos nódulos hepáticos sólidos; considerar a possibilidade de lesões secundárias.'},
  {o:'figado', n:'Lesão cística complexa (abscesso?)', m:'add',
   t:'Lesão cística de paredes espessas e irregulares, com conteúdo espesso e debris, no segmento XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Lesão cística complexa no segmento {0}; considerar abscesso, a critério clínico.'},
  {o:'figado', n:'Lobo de Riedel', m:'add',
   t:'Alongamento do lobo hepático direito, medindo XXX cm no eixo longitudinal, com morfologia preservada (variante anatômica — lobo de Riedel).',
   c:''},
  {o:'figado', n:'Avaliação limitada por esteatose', m:'add',
   t:'A atenuação do feixe acústico pela alteração difusa reduz a sensibilidade do método para lesões focais.', c:''},

  /* ---------------- VEIAS PORTA / HEPÁTICAS ---------------- */
  {o:'porta', n:'Hipertensão portal', m:'sub',
   t:'veia porta com calibre aumentado, medindo XXX cm, e vasos colaterais dilatados e tortuosos no território XXX. Veias hepáticas pérvias.',
   c:'Sinais de hipertensão portal.'},
  {o:'porta', n:'Trombose da veia porta', m:'sub',
   t:'veia porta com calibre de XXX cm, preenchida por material ecogênico no segmento extra-hepático XX intra-hepático. Veias hepáticas com calibres preservados.',
   c:'Sinais de trombose da veia porta.'},
  {o:'porta', s:1, n:'Congestão (veias hepáticas dilatadas)', m:'sub',
   t:'veia porta com calibre preservado. Veias hepáticas e veia cava inferior dilatadas.',
   c:'Dilatação das veias hepáticas e da veia cava inferior, que pode estar relacionada a congestão hepática.'},

  /* ---------------- VESÍCULA BILIAR ---------------- */
  {o:'vesicula', s:1, n:'Colelitíase (cálculo único)', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo cálculo móvel com sombra acústica posterior, medindo XXX cm.',
   c:'Colelitíase.'},
  {o:'vesicula', s:1, n:'Colelitíase (múltiplos)', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo múltiplos cálculos móveis com sombra acústica posterior, o maior medindo XXX cm.',
   c:'Colelitíase.'},
  {o:'vesicula', n:'Colelitíase + lama biliar', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo material ecogênico pendente sem sombra (lama biliar) e cálculo(s) com sombra acústica posterior, o maior medindo XXX cm.',
   c:'Colelitíase e lama biliar.'},
  {o:'vesicula', s:1, n:'Lama biliar', m:'sub',
   t:'tópica, normodistendida, com paredes finas e regulares, contendo material ecogênico pendente, sem sombra acústica, formando nível líquido-líquido (lama biliar).',
   c:'Lama biliar. A lama pode mascarar microcálculos.'},
  {o:'vesicula', s:1, n:'Colecistite aguda litiásica', m:'sub',
   t:'distendida, com paredes espessadas e edemaciadas, medindo até XXX cm, contendo cálculo(s) com sombra acústica, o maior medindo XXX cm. Sinal de Murphy ultrassonográfico positivo.',
   c:'Achados sugestivos de colecistite aguda litiásica.'},
  {o:'vesicula', n:'Vesícula escleroatrófica', m:'sub',
   t:'contraída, com lúmen ocupado por cálculo(s) e extensa sombra acústica posterior (complexo parede-eco-sombra), medindo cerca de XXX cm.',
   c:'Colelitíase com vesícula biliar escleroatrófica.'},
  {o:'vesicula', s:1, n:'Pólipo', m:'add',
   t:'Imagem polipoide ecogênica, fixa, sem sombra acústica, aderida à parede XXX, medindo XXX cm.',
   c:'Pólipo na vesícula biliar ({1} cm).'},
  {o:'vesicula', n:'Colesterolose', m:'add',
   t:'Pequenos focos ecogênicos parietais com artefato em cauda de cometa, sem cálculos.',
   c:'Colesterolose vesicular.'},
  {o:'vesicula', n:'Adenomiomatose', m:'add',
   t:'Espessamento parietal segmentar XX difuso XX fúndico, de até XXX cm, com pequenos espaços císticos e focos com artefato em cauda de cometa.',
   c:'Achados sugestivos de adenomiomatose da vesícula biliar.'},
  {o:'vesicula', s:1, n:'Colecistectomia', m:'sub',
   t:'não caracterizada (status pós-colecistectomia).',
   c:'Status pós-colecistectomia.'},

  /* ---------------- VIAS BILIARES ---------------- */
  {o:'vias', s:1, n:'Dilatação intra e extra-hepática', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm.',
   c:'Dilatação das vias biliares intra e extra-hepáticas.'},
  {o:'vias', s:1, n:'Coledocolitíase', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm e imagem ecogênica com sombra acústica em sua porção distal, medindo XXX cm, sugestiva de cálculo.',
   c:'Dilatação das vias biliares por provável coledocolitíase.'},
  {o:'vias', n:'Dilatação com obstrução distal', m:'sub',
   t:'dilatadas, com colédoco medindo XXX cm, com afilamento abrupto distal junto à cabeça pancreática.',
   c:'Dilatação das vias biliares com afilamento distal; prosseguir investigação com método seccional.'},
  {o:'vias', n:'Dilatação intra-hepática hilar', m:'sub',
   t:'dilatação das vias biliares intra-hepáticas, com aparente interrupção na região hilar; colédoco de calibre preservado.',
   c:'Dilatação das vias biliares intra-hepáticas com obstrução hilar; prosseguir investigação com método seccional.'},
  {o:'vias', n:'Aerobilia', m:'add',
   t:'Focos ecogênicos lineares com artefato de reverberação nas vias biliares, compatíveis com aerobilia.',
   c:'Aerobilia.'},

  /* ---------------- PÂNCREAS ---------------- */
  {o:'pancreas', s:1, n:'Não caracterizado (gases)', m:'sub',
   t:'não caracterizado devido à interposição gasosa intestinal.', c:''},
  {o:'pancreas', n:'Parcialmente avaliado (gases)', m:'sub',
   t:'cabeça e corpo com dimensões, contornos e ecogenicidade normais; cauda não caracterizada devido à interposição gasosa.', c:''},
  {o:'pancreas', s:1, n:'Lipossubstituição', m:'sub',
   t:'com dimensões e contornos normais e ecogenicidade difusamente aumentada.',
   c:'Aumento difuso da ecogenicidade pancreática, compatível com lipossubstituição.'},
  {o:'pancreas', n:'Pancreatite aguda (padrão)', m:'sub',
   t:'com dimensões aumentadas, ecogenicidade reduzida e contornos borrados, com líquido peripancreático.',
   c:'Alterações pancreáticas que podem corresponder a pancreatite aguda, a critério clínico-laboratorial.'},
  {o:'pancreas', n:'Pancreatopatia crônica', m:'sub',
   t:'com contornos lobulados, calcificações parenquimatosas e ducto pancreático principal dilatado, medindo XXX cm.',
   c:'Sinais de pancreatopatia crônica.'},
  {o:'pancreas', s:1, n:'Lesão cística', m:'add',
   t:'Imagem cística na cabeça XX corpo XX cauda pancreática, medindo XXX cm.',
   c:'Lesão cística pancreática. Sugere-se complementação com RM.'},
  {o:'pancreas', n:'Massa sólida', m:'add',
   t:'Massa sólida hipoecogênica na cabeça XX corpo XX cauda pancreática, medindo XXX cm.',
   c:'Massa sólida pancreática; prosseguir investigação com método seccional.'},

  /* ---------------- BAÇO ---------------- */
  {o:'baco', s:1, n:'Esplenomegalia', m:'sub',
   t:'com dimensões aumentadas, medindo XXX cm no maior eixo, homogêneo.',
   c:'Esplenomegalia ({0} cm).'},
  {o:'baco', s:1, n:'Baço acessório', m:'add',
   t:'Pequeno nódulo junto ao hilo esplênico, com ecogenicidade semelhante à do baço, medindo XXX cm, compatível com baço acessório.',
   c:''},
  {o:'baco', s:1, n:'Granulomas calcificados', m:'add',
   t:'Focos hiperecogênicos esparsos com sombra acústica posterior, compatíveis com granulomas calcificados.',
   c:'Granulomas calcificados esplênicos.'},
  {o:'baco', n:'Hemangioma', m:'add',
   t:'Nódulo hiperecogênico, homogêneo e bem definido no terço superior XX médio XX inferior, medindo XXX cm.',
   c:'Nódulo esplênico com aspecto sugestivo de hemangioma.'},
  {o:'baco', s:1, n:'Esplenectomia', m:'sub',
   t:'não caracterizado (status pós-esplenectomia).',
   c:'Status pós-esplenectomia.'},
  {o:'baco', n:'Esplenose', m:'add',
   t:'Nódulos sólidos com ecotextura semelhante à esplênica na loja esplênica, medindo até XXX cm.',
   c:'Nódulos na loja esplênica, sugestivos de esplenose.'},

  /* ---------------- RINS ---------------- */
  {o:'rins', x:['cálculos','cálculo'], s:1, n:'Cálculo não obstrutivo', m:'add',
   t:'Cálculo no grupo calicinal superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm, sem dilatação do sistema coletor.',
   c:'Nefrolitíase não obstrutiva no rim {1}.'},
  {o:'rins', n:'Foco ecogênico sem sombra (cálculo?)', m:'add',
   t:'Pequeno foco ecogênico sem sombra acústica no rim direito XX esquerdo, medindo XXX cm.',
   c:'Pequeno foco ecogênico renal; não se pode excluir microcálculo.'},
  {o:'rins', x:['hidronefrose','dilatação'], s:1, n:'Hidronefrose', m:'add',
   t:'Dilatação leve XX moderada XX acentuada do sistema pielocalicinal do rim direito XX esquerdo.',
   c:'Hidronefrose {0} no rim {1}.'},
  {o:'rins', x:['hidronefrose','dilatação','cálculos','cálculo'], n:'Ureterolitíase com dilatação', m:'add',
   t:'Cálculo no ureter proximal XX distal direito XX esquerdo, medindo XXX cm, com uretero-hidronefrose a montante.',
   c:'Ureterolitíase no ureter {0} {1}, com uretero-hidronefrose a montante.'},
  {o:'rins', s:1, n:'Cisto renal simples', m:'add',
   t:'Cisto simples no terço superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm.',
   c:'Cisto renal simples no rim {1}.'},
  {o:'rins', n:'Rins policísticos', m:'sub',
   t:'tópicos, aumentados, com múltiplos cistos de tamanhos variados substituindo o parênquima bilateralmente, o maior medindo XXX cm.',
   c:'Múltiplos cistos renais bilaterais; considerar doença renal policística.'},
  {o:'rins', n:'Angiomiolipoma', m:'add',
   t:'Nódulo hiperecogênico, homogêneo e bem definido no terço superior XX médio XX inferior do rim direito XX esquerdo, medindo XXX cm.',
   c:'Nódulo renal com aspecto sugestivo de angiomiolipoma.'},
  {o:'rins', n:'Nefropatia crônica', m:'sub',
   t:'tópicos, com dimensões reduzidas (RD = XXX cm; RE = XXX cm), contornos irregulares, ecogenicidade parenquimatosa aumentada e redução da diferenciação corticomedular.',
   c:'Sinais de nefropatia parenquimatosa crônica bilateral.'},
  {o:'rins', n:'Nefrocalcinose medular', m:'add',
   t:'Pirâmides renais hiperecogênicas bilateralmente, com tênue sombra acústica.',
   c:'Sinais de nefrocalcinose medular.'},
  {o:'rins', n:'Duplicidade pielocalicinal', m:'add',
   t:'Seio renal com banda de parênquima separando os grupos calicinais no rim direito XX esquerdo, sugerindo duplicidade pielocalicinal.',
   c:''},
  {o:'rins', n:'Rim pélvico', m:'add',
   t:'Rim direito XX esquerdo em topografia pélvica, medindo XXX cm.',
   c:'Rim {0} ectópico pélvico.'},
  {o:'rins', n:'Rim em ferradura', m:'add',
   t:'Polos inferiores renais unidos por istmo de parênquima anterior à aorta.',
   c:'Rim em ferradura.'},
  {o:'rins', s:1, n:'Nefrectomia', m:'add',
   t:'Rim direito XX esquerdo não caracterizado (status pós-nefrectomia).',
   c:'Status pós-nefrectomia (rim {0}).'},
  {o:'rins', n:'Agenesia?', m:'add',
   t:'Rim direito XX esquerdo não caracterizado na loja renal nem na pelve.',
   c:'Rim {0} não caracterizado; considerar agenesia ou ectopia.'},
  {o:'rins', n:'Cateter duplo J', m:'add',
   t:'Cateter de duplo J à direita XX esquerda, com extremidades no sistema pielocalicinal e na bexiga.',
   c:'Cateter de duplo J à {0}.'},

  /* ---------------- BEXIGA ---------------- */
  {o:'bexiga', n:'Espessamento difuso (esforço)', m:'sub',
   t:'com paredes difusamente espessadas e trabeculadas, medindo até XXX cm, com pseudodivertículos.',
   c:'Bexiga de esforço.'},
  {o:'bexiga', n:'Espessamento difuso (cistite?)', m:'sub',
   t:'com paredes difusamente espessadas, medindo até XXX cm, e conteúdo anecogênico.',
   c:'Espessamento parietal vesical difuso; considerar cistite, a critério clínico.'},
  {o:'bexiga', x:[], s:1, n:'Cálculo vesical', m:'add',
   t:'Imagem ecogênica móvel com sombra acústica em seu interior, medindo XXX cm.',
   c:'Litíase vesical.'},
  {o:'bexiga', n:'Lesão parietal vegetante', m:'add',
   t:'Lesão sólida vegetante, fixa, na parede XXX, medindo XXX cm.',
   c:'Lesão vegetante vesical; prosseguir investigação (cistoscopia).'},
  {o:'bexiga', n:'Coágulo', m:'add',
   t:'Material ecogênico heterogêneo, móvel, no assoalho vesical, medindo XXX cm, sugestivo de coágulo.',
   c:'Imagem sugestiva de coágulo intravesical.'},
  {o:'bexiga', s:1, n:'Sonda vesical', m:'add',
   t:'Balão de sonda vesical no interior da bexiga.', c:''},
  {o:'bexiga', n:'Resíduo pós-miccional', m:'add',
   t:'Resíduo pós-miccional estimado em XXX mL.',
   c:'Resíduo pós-miccional de {0} mL.'},

  /* ---------------- PRÓSTATA ---------------- */
  {o:'prostata', n:'Aumentada (hiperplasia)', m:'sub',
   t:'com dimensões aumentadas, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³), ecotextura heterogênea e contornos regulares.',
   c:'Próstata aumentada ({3} cm³).'},
  {o:'prostata', n:'Calcificações', m:'add',
   t:'Focos de calcificação no parênquima prostático.', c:''},
  {o:'prostata', n:'Protrusão intravesical', m:'add',
   t:'Protrusão do lobo mediano na base vesical, medindo XXX cm.',
   c:'Protrusão prostática intravesical ({0} cm).'},

  /* ---------------- AORTA ---------------- */
  {o:'aorta', s:1, n:'Ateromatose', m:'sub',
   t:'com calibre normal e placas parietais calcificadas.', c:'Ateromatose aórtica.'},
  {o:'aorta', s:1, n:'Aneurisma', m:'sub',
   t:'com dilatação aneurismática fusiforme XX sacular no segmento infrarrenal, medindo XXX cm de diâmetro máximo e XXX cm de extensão.',
   c:'Aneurisma da aorta abdominal infrarrenal ({1} cm).'},
  {o:'aorta', s:1, n:'Aneurisma com trombo mural', m:'add',
   t:'Trombo mural laminar reduzindo parcialmente a luz.', c:''},

  /* ---------------- PERITÔNEO / RETROPERITÔNIO ---------------- */
  {o:'peritoneo', s:1, n:'Ascite', m:'sub',
   t:'pequena XX moderada XX grande quantidade de líquido livre na cavidade abdominal.',
   c:'Ascite ({0} quantidade).'},
  {o:'peritoneo', n:'Líquido com debris (sangue?)', m:'sub',
   t:'líquido livre com debris na cavidade abdominal, em quantidade pequena XX moderada XX grande.',
   c:'Líquido livre com debris; considerar hemoperitônio, a critério clínico.'},
  {o:'peritoneo', x:['coleções','coleção'], s:1, n:'Coleção', m:'add',
   t:'Coleção em XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Coleção em {0}.'},
  {o:'peritoneo', s:1, n:'Linfonodomegalia retroperitoneal', m:'add',
   t:'Linfonodos retroperitoneais aumentados, o maior medindo XXX cm no menor eixo.',
   c:'Linfonodomegalia retroperitoneal.'},

  /* ---------------- ACHADOS ADICIONAIS (abdome) ---------------- */
  {o:'__extra', n:'Apendicite (padrão)', m:'add',
   t:'Estrutura tubular em fundo cego na fossa ilíaca direita, não compressível, com diâmetro de XXX cm, com borramento da gordura adjacente.',
   c:'Achados sugestivos de apendicite aguda.'},
  {o:'__extra', n:'Apêndice não caracterizado', m:'add',
   t:'Apêndice cecal não caracterizado; sem borramento da gordura ou coleções na fossa ilíaca direita.',
   c:''},
  {o:'__extra', n:'Adenite mesentérica', m:'add',
   t:'Linfonodos mesentéricos aumentados na fossa ilíaca direita, o maior medindo XXX cm no menor eixo, sem borramento da gordura.',
   c:'Linfonodos mesentéricos aumentados; considerar adenite mesentérica.'},
  {o:'__extra', n:'Intussuscepção', m:'add',
   t:'Imagem em alvo no XXX, medindo XXX cm, compatível com invaginação intestinal.',
   c:'Sinais de intussuscepção intestinal.'},
  {o:'__extra', n:'Espessamento de alça', m:'add',
   t:'Espessamento parietal de alça XXX, medindo até XXX cm, com borramento da gordura adjacente.',
   c:'Espessamento parietal de alça intestinal; considerar processo inflamatório/infeccioso.'},
  {o:'__extra', n:'Hérnia', m:'add',
   t:'Hérnia XXX com colo de XXX cm, contendo gordura XX intestino, redutível XX irredutível.',
   c:'Hérnia {0}.'},

  /* ---------------- TIREOIDE ---------------- */
  {o:'tireoide', x:['lesões nodulares','císticas'], n:'Nódulo', m:'add',
   t:'Nódulo sólido XX misto XX cístico no terço superior XX médio XX inferior do lobo direito XX esquerdo, medindo XXX x XXX x XXX cm. ACR TI-RADS: XXX.',
   c:'Nódulo tireoidiano no lobo {2} (TI-RADS {6}).'},
  {o:'tireoide', x:['lesões nodulares','císticas'], n:'Cisto', m:'add',
   t:'Cisto anecogênico no lobo direito XX esquerdo, medindo XXX cm.',
   c:'Cisto tireoidiano.'},
  {o:'tireoide', n:'Bócio', m:'sub',
   t:'tópica, com dimensões aumentadas (volume total de XXX cm³), contornos regulares e textura heterogênea.',
   c:'Bócio.'},
  {o:'tireoide', n:'Tireoidopatia difusa', m:'sub',
   t:'tópica, com dimensões normais XX aumentadas XX reduzidas, textura difusamente heterogênea e vascularização aumentada XX preservada ao Doppler.',
   c:'Tireoidopatia difusa; correlacionar com função tireoidiana e anticorpos.'},
  {o:'tireoide', n:'Tireoidectomia total', m:'sub',
   t:'não caracterizada (status pós-tireoidectomia total).', c:'Status pós-tireoidectomia total.'},
  {o:'tireoide', n:'Tireoidectomia parcial', m:'add',
   t:'Lobo direito XX esquerdo não caracterizado (status pós-operatório).', c:'Status pós-lobectomia tireoidiana (lobo {0}).'},

  /* ---------------- LINFONODOS (cervical etc.) ---------------- */
  {o:'linfonodos', n:'Linfonodos de aspecto reacional', m:'sub',
   t:'linfonodos de aspecto habitual (hilo ecogênico preservado) no nível XXX, o maior medindo XXX cm no menor eixo.', c:''},
  {o:'linfonodos', n:'Linfonodomegalia suspeita', m:'sub',
   t:'linfonodos aumentados, arredondados, com perda do hilo ecogênico, no nível XXX, o maior medindo XXX cm no menor eixo.',
   c:'Linfonodomegalia de aspecto suspeito no nível {0}.'},

  /* ---------------- GLÂNDULAS SALIVARES ---------------- */
  {o:'salivares', n:'Sialoadenite', m:'add',
   t:'Glândula parótida XX submandibular direita XX esquerda aumentada, heterogênea e hipervascularizada ao Doppler.',
   c:'Sinais de sialoadenite.'},
  {o:'salivares', n:'Sialolitíase', m:'add',
   t:'Cálculo no ducto da glândula XXX, medindo XXX cm, com dilatação ductal a montante.',
   c:'Sialolitíase.'},
  {o:'salivares', n:'Nódulo', m:'add',
   t:'Nódulo sólido na glândula XXX, medindo XXX cm.',
   c:'Nódulo em glândula salivar; prosseguir investigação.'},

  /* ---------------- BOLSA TESTICULAR ---------------- */
  {o:'testiculo', n:'Hidrocele', m:'add',
   t:'Pequena XX moderada XX grande quantidade de líquido anecogênico na túnica vaginal à direita XX esquerda.',
   c:'Hidrocele à {1}.'},
  {o:'testiculo', n:'Varicocele', m:'add',
   t:'Veias do plexo pampiniforme à direita XX esquerda dilatadas, medindo até XXX cm, com refluxo à manobra de Valsalva.',
   c:'Varicocele à {0}.'},
  {o:'testiculo', n:'Cisto de epidídimo', m:'add',
   t:'Cisto na cabeça do epidídimo direito XX esquerdo, medindo XXX cm.',
   c:'Cisto de epidídimo.'},
  {o:'testiculo', n:'Microlitíase', m:'add',
   t:'Múltiplos pequenos focos ecogênicos sem sombra acústica no parênquima testicular direito XX esquerdo XX bilateral.',
   c:'Microlitíase testicular.'},
  {o:'testiculo', n:'Nódulo testicular', m:'add',
   t:'Nódulo sólido hipoecogênico no testículo direito XX esquerdo, medindo XXX cm, com fluxo ao Doppler.',
   c:'Nódulo testicular sólido; correlação com marcadores e avaliação urológica.'},
  {o:'testiculo', n:'Orquiepididimite (padrão)', m:'add',
   t:'Epidídimo e testículo direito XX esquerdo aumentados, heterogêneos e hipervascularizados ao Doppler.',
   c:'Sinais de orquiepididimite (lado {0}).'},
  {o:'testiculo', n:'Ausência de fluxo (torção?)', m:'add',
   t:'Testículo direito XX esquerdo heterogêneo, sem fluxo detectável ao Doppler, com funículo espermático espiralado.',
   c:'Achados compatíveis com torção do testículo {0}. Avaliação urológica imediata.'},

  /* ---------------- ÚTERO / ENDOMÉTRIO / OVÁRIOS ---------------- */
  {o:'utero', x:['nódulos'], n:'Mioma', m:'add',
   t:'Nódulo miometrial hipoecogênico XX heterogêneo XX isoecogênico, intramural XX subseroso XX submucoso, na parede XXX, medindo XXX x XXX x XXX cm.',
   c:'Mioma uterino.'},
  {o:'utero', x:['nódulos'], n:'Miomas (vários)', m:'add',
   t:'Múltiplos nódulos miometriais, o maior intramural XX subseroso XX submucoso na parede XXX, medindo XXX cm.',
   c:'Útero miomatoso.'},
  {o:'utero', n:'Adenomiose (padrão)', m:'add',
   t:'Miométrio heterogêneo, com assimetria das paredes, pequenos cistos e estrias ecogênicas.',
   c:'Achados sugestivos de adenomiose.'},
  {o:'utero', n:'Histerectomia', m:'sub',
   t:'não caracterizado (status pós-histerectomia).', c:'Status pós-histerectomia.'},
  {o:'utero', n:'Nicho de cesárea', m:'add',
   t:'Falha miometrial em forma de nicho na cicatriz de cesárea, com miométrio residual de XXX cm.',
   c:'Nicho na cicatriz de cesárea (istmocele).'},
  {o:'endometrio', n:'Espessado', m:'sub',
   t:'centrado, espessado e heterogêneo XX homogêneo, medindo XXX cm.',
   c:'Espessamento endometrial ({1} cm).'},
  {o:'endometrio', n:'Pólipo endometrial', m:'add',
   t:'Imagem ecogênica intracavitária com pedículo vascular ao Doppler, medindo XXX cm.',
   c:'Imagem sugestiva de pólipo endometrial.'},
  {o:'endometrio', n:'Restos ovulares', m:'add',
   t:'Material heterogêneo na cavidade endometrial, medindo XXX cm, com fluxo ao Doppler.',
   c:'Material heterogêneo intracavitário; considerar restos ovulares.'},
  {o:'ovario', n:'Cisto simples', m:'add',
   t:'Cisto simples anecogênico, de paredes finas, medindo XXX cm.',
   c:'Cisto ovariano simples.'},
  {o:'ovario', n:'Cisto hemorrágico', m:'add',
   t:'Imagem cística com finos ecos reticulares, sem fluxo interno, medindo XXX cm.',
   c:'Imagem cística com aspecto sugestivo de cisto hemorrágico.'},
  {o:'ovario', n:'Corpo lúteo', m:'add',
   t:'Corpo lúteo com vascularização periférica, medindo XXX cm.', c:''},
  {o:'ovario', n:'Endometrioma', m:'add',
   t:'Imagem cística com conteúdo de ecos finos homogêneos (vidro fosco), medindo XXX cm.',
   c:'Imagem cística com aspecto sugestivo de endometrioma.'},
  {o:'ovario', n:'Padrão micropolicístico', m:'add',
   t:'Múltiplos folículos periféricos (XXX folículos), com estroma ecogênico.',
   c:'Ovário de aspecto micropolicístico.'},
  {o:'ovario', n:'Lesão complexa', m:'add',
   t:'Lesão cística complexa com componente sólido, medindo XXX cm. O-RADS US: XXX.',
   c:'Lesão anexial complexa (O-RADS US {1}).'},
  {o:'ovario', n:'Não caracterizado', m:'sub',
   t:'não caracterizado (motivo: XXX).', c:''},

  /* ---------------- PARTES MOLES ---------------- */
  {o:'partes', n:'Lipoma', m:'add',
   t:'Nódulo ovalado no subcutâneo, isoecogênico à gordura, com finas estrias, sem fluxo ao Doppler, medindo XXX x XXX cm.',
   c:'Nódulo com aspecto sugestivo de lipoma.'},
  {o:'partes', n:'Cisto epidérmico', m:'add',
   t:'Nódulo hipoecogênico bem definido na derme/subcutâneo, com reforço acústico posterior, medindo XXX cm.',
   c:'Nódulo com aspecto sugestivo de cisto epidérmico.'},
  {o:'partes', n:'Coleção / abscesso', m:'add',
   t:'Coleção com conteúdo espesso e debris em XXX, medindo XXX x XXX x XXX cm (volume estimado em XXX cm³).',
   c:'Coleção em {0}.'},
  {o:'partes', n:'Edema do subcutâneo', m:'add',
   t:'Espessamento e aumento da ecogenicidade do subcutâneo com faixas líquidas de permeio (padrão em paralelepípedo).',
   c:'Edema do tecido subcutâneo.'},
  {o:'partes', n:'Hematoma', m:'add',
   t:'Coleção heterogênea, sem fluxo ao Doppler, em XXX, medindo XXX x XXX x XXX cm.',
   c:'Coleção com aspecto sugestivo de hematoma.'},

  /* ---------------- TÓRAX ---------------- */
  {o:'pleura', n:'Derrame pleural', m:'add',
   t:'Derrame pleural à direita XX esquerda, em pequena XX moderada XX grande quantidade, anecogênico.',
   c:'Derrame pleural à {0}.'},
  {o:'pleura', n:'Derrame com atelectasia', m:'add',
   t:'Derrame pleural à direita XX esquerda com atelectasia passiva do parênquima adjacente.',
   c:'Derrame pleural à {0} com atelectasia adjacente.'},
];

function lauFraseOrgao(label){
  const n = String(label||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().trim();
  const hit = LAU_FRASE_ORGAOS.find(o=>o[1].test(n));
  return hit ? hit[0] : null;
}
function lauFrasesDe(org){ return LAU_FRASES.map((f,i)=>Object.assign({i},f)).filter(f=>f.o===org); }
